version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      sing-box-stack:
        patterns:
          - "github.com/sagernet/sing"
          - "github.com/sagernet/sing-*"
          - "github.com/sagernet/cronet-go*"
          - "github.com/quic-go/quic-go"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/mobile"
    schedule:
      interval: "daily"
