import 'package:flutter/material.dart';

class AppLanguage {
  const AppLanguage(this.code, this.label);
  final String code;
  final String label;
}

class AppLocalizations {
  static const languages = <AppLanguage>[
    AppLanguage('en', 'English'),
    AppLanguage('zhHans', '简体中文'),
    AppLanguage('zhHant', '繁體中文'),
    AppLanguage('ja', '日本語'),
    AppLanguage('fr', 'Français'),
    AppLanguage('la', 'Latina'),
    AppLanguage('fa', 'فارسی'),
    AppLanguage('vi', 'Tiếng Việt'),
    AppLanguage('ru', 'Русский'),
  ];

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'),
    Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'),
    Locale('ja'),
    Locale('fr'),
    Locale('fa'),
    Locale('vi'),
    Locale('ru'),
  ];

  static Locale localeOf(String code) => switch (code) {
        'zhHans' => const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'),
        'zhHant' => const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'),
        'la' => const Locale('en'),
        _ => Locale(code),
      };

  static String bestMatch(Locale locale) {
    if (locale.languageCode == 'zh') {
      return locale.scriptCode == 'Hant' ? 'zhHant' : 'zhHans';
    }
    if (languages.any((item) => item.code == locale.languageCode)) return locale.languageCode;
    return 'en';
  }

  static String tr(String code, String key, {Map<String, Object?> args = const {}}) {
    final value = (_messages[code] ?? _messages['en'] ?? const {})[key] ?? _messages['en']?[key] ?? key;
    return args.entries.fold(value, (text, entry) => text.replaceAll('{${entry.key}}', entry.value?.toString() ?? ''));
  }

  static String fieldLabel(String code, String key) {
    final map = code == 'zhHans' || code == 'zhHant' ? _fieldLabelsZhHans : _fieldLabelsEn;
    return map[key] ?? _fieldLabelsEn[key] ?? key.replaceAll('_', ' ');
  }

  static String singularLabel(String code, String key) {
    final map = code == 'zhHans' || code == 'zhHant' ? _singularLabelsZhHans : _singularLabelsEn;
    return map[key] ?? _singularLabelsEn[key] ?? tr(code, 'editor.item');
  }
}

const _en = <String, String>{
  'app.name': 'S-UI',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.delete': 'Delete',
  'common.refresh': 'Refresh',
  'common.refreshed': 'Refreshed',
  'common.search': 'Search',
  'common.from': 'From',
  'common.to': 'To',
  'common.all': 'All',
  'common.none': 'None',
  'common.details': 'Details',
  'common.result': 'Result',
  'common.language': 'Language',
  'nav.home': 'Home',
  'nav.clients': 'Users',
  'nav.inbounds': 'Inbounds',
  'nav.outbounds': 'Outbounds',
  'nav.endpoints': 'Nodes',
  'nav.services': 'Services',
  'nav.tls': 'TLS',
  'nav.config': 'Core config',
  'nav.analytics': 'Usage & Stats',
  'nav.logs': 'Logs',
  'nav.admin': 'Admins',
  'nav.tools': 'Settings & Tools',
  'nav.logout': 'Exit current connection',
  'nav.logoutTitle': 'Exit connection',
  'nav.logoutMessage': 'Also revoke the current mobile API token?',
  'nav.logoutRevoke': 'Revoke and exit',
  'auth.passkey': 'Passkey',
  'connect.title': 'Connect to S-UI',
  'connect.subtitle': 'Connection details and tokens are stored only in system secure storage.',
  'connect.name': 'Connection name',
  'connect.defaultName': 'My S-UI',
  'connect.panelUrl': 'Panel URL (including web path)',
  'connect.passwordLogin': 'Password login',
  'connect.adminUsername': 'Admin username',
  'connect.adminPassword': 'Admin password',
  'connect.secondFactor': '2FA code or recovery code',
  'connect.customHeaders': 'Custom request headers',
  'connect.cfPreset': 'Cloudflare Access Service Token fields are prefilled',
  'connect.headerName': 'Header name',
  'connect.headerValue': 'Header value',
  'connect.addHeader': 'Add header',
  'connect.verifying': 'Verifying…',
  'connect.connect': 'Connect panel',
  'connect.httpsHint': 'HTTPS is recommended. For Cloudflare Zero Trust, fill CF-Access-Client-Id and CF-Access-Client-Secret.',
  'dashboard.title': 'Runtime overview',
  'dashboard.restartCore': 'Restart sing-box',
  'dashboard.running': 'Running',
  'dashboard.stopped': 'Stopped',
  'dashboard.memory': 'Memory',
  'dashboard.disk': 'Disk',
  'dashboard.totalUpload': 'Total upload',
  'dashboard.totalDownload': 'Total download',
  'dashboard.resources': 'Resources',
  'dashboard.users': 'Users',
  'dashboard.inbounds': 'Inbounds',
  'dashboard.outbounds': 'Outbounds',
  'dashboard.nodes': 'Nodes',
  'dashboard.services': 'Services',
  'dashboard.onlineStatus': 'Online status',
  'dashboard.restartConfirm': 'Existing connections may be briefly interrupted.',
  'dashboard.restartSubmitted': 'Restart submitted',
  'dashboard.noOnline': 'No online items',
  'resource.subtitle': 'Full-field editing and search, compatible with new sing-box protocol fields',
  'resource.bulk': 'Bulk operation',
  'resource.new': 'New',
  'resource.search': 'Search {title}',
  'resource.empty': 'No matching data',
  'resource.deleteTitle': 'Delete {title}',
  'resource.deleteMessage': 'This will immediately update the sing-box configuration.',
  'resource.deleted': 'Deleted',
  'resource.bulkAdd': 'Bulk add',
  'resource.bulkEdit': 'Bulk edit',
  'resource.bulkDelete': 'Bulk delete',
  'resource.action': 'Action',
  'resource.jsonArray': 'JSON array',
  'resource.execute': 'Execute',
  'resource.checkOk': 'Connection OK{delay}',
  'resource.checkFailed': 'Test failed',
  'resource.userNotFound': 'User details not found',
  'resource.subscription': 'Subscription',
  'resource.jsonSubscription': 'JSON subscription',
  'resource.clashSubscription': 'Clash subscription',
  'resource.singboxImport': 'Sing-box import',
  'resource.shareLink': 'Share link',
  'resource.qrcode': 'QR code',
  'resource.noLinks': 'No displayable links',
  'resource.copied': 'Copied',
  'resource.copy': 'Copy',
  'resource.noWireguardPeers': 'No available WireGuard peer configuration',
  'resource.edit': 'Edit',
  'resource.clone': 'Clone',
  'resource.connectionTest': 'Connection test',
  'resource.subscriptionQr': 'Subscription & QR code',
  'resource.wireguardQr': 'WireGuard QR code',
  'resource.copyJson': 'Copy JSON',
  'resource.jsonCopied': 'JSON copied',
  'config.title': 'Core config',
  'config.subtitle': 'Manage basics, DNS, routing, experimental features and panel settings.',
  'config.basics': 'Basics',
  'config.routing': 'Routing',
  'config.experimental': 'Experimental',
  'config.panelSettings': 'Panel settings',
  'config.basicInfo': 'Basic information',
  'config.routingRulesets': 'Routing & rulesets',
  'config.edit': 'Edit',
  'config.editAllSettings': 'Edit all settings',
  'config.panelSubscriptionSettings': 'Panel & subscription settings',
  'config.configObjectRequired': 'Config must be a JSON object',
  'config.settingsObjectRequired': 'Settings must be a JSON object',
  'config.panelInterface': 'Panel interface',
  'config.subscriptionService': 'Subscription service',
  'config.subscriptionExtensions': 'Subscription extensions',
  'config.loginIdentity': 'Login & identity',
  'editor.visual': 'Visual',
  'editor.jsonError': 'JSON error: {error}',
  'editor.visualHint': 'Edit with options, switches and inputs; new sing-box fields can still be maintained with “Add field” or JSON mode.',
  'editor.needObject': 'Visual editing requires a JSON object. Switch to JSON mode.',
  'editor.deleteItem': 'Delete item',
  'editor.addItem': 'Add {item}',
  'editor.deleteField': 'Delete field',
  'editor.addField': 'Add field',
  'editor.addConfigField': 'Add config field',
  'editor.commonField': 'Common field (optional)',
  'editor.fieldName': 'Field name',
  'editor.fieldsCount': '{count} fields',
  'editor.itemsCount': '{count} items',
  'editor.onePerLine': 'One item per line',
  'editor.item': 'Item',
  'editor.valueType': 'Value type',
  'editor.text': 'Text',
  'editor.number': 'Number',
  'editor.bool': 'Switch',
  'editor.object': 'Object',
  'editor.list': 'List',
  'analytics.title': 'Usage & Stats',
  'analytics.subtitle': 'Filter by user, date and keyword; inspect traffic and connection details.',
  'analytics.userUsage': 'User usage',
  'analytics.trafficTrends': 'Traffic trends',
  'analytics.connections': 'Connections',
  'analytics.userExact': 'User / tag (exact, optional)',
  'analytics.resource': 'Resource',
  'analytics.upload': 'Upload',
  'analytics.download': 'Download',
  'analytics.total': 'Total',
  'analytics.usersCount': '{count} users',
  'analytics.noUsage': 'No usage data in this range',
  'analytics.noStats': 'No traffic statistics in this range',
  'analytics.noConnections': 'No connection logs in this range',
  'analytics.quota': 'Selected range / quota {quota}',
  'analytics.expiry': 'Expiry {time}',
  'analytics.allTags': 'All tags',
  'analytics.scanned': 'Scanned {count} INFO logs',
  'analytics.inbounds': 'Inbounds',
  'analytics.outbounds': 'Outbounds',
  'analytics.nodes': 'Nodes',
  'analytics.destinations': 'Destinations',
  'analytics.lastSeen': 'Last seen',
  'analytics.connectionDetails': 'Connection details',
  'logs.title': 'Logs',
  'logs.subtitle': 'Search system logs and audit changes. DEBUG, INFO, WARNING and ERROR are supported.',
  'logs.fullText': 'Full-text search',
  'logs.user': 'User / admin',
  'logs.level': 'Level',
  'logs.empty': 'No matching logs',
  'logs.count': '{count} entries',
  'tools.title': 'Settings & Tools',
  'tools.subtitle': 'Connection, backup, converters and service operations.',
  'tools.currentConnection': 'Current connection',
  'tools.customHeaders': 'Custom headers',
  'tools.noHeaders': 'Not configured',
  'tools.reconfigure': 'Reconfigure connection',
  'tools.reconfigureHint': 'Return to the connection screen to change URL, token or Cloudflare headers.',
  'tools.backupRestore': 'Backup & restore',
  'tools.exportDatabase': 'Export database',
  'tools.restoreDatabase': 'Restore database',
  'tools.exportSingbox': 'Export sing-box config',
  'tools.conversionKeys': 'Conversion & keys',
  'tools.linkConvert': 'Share link to outbound',
  'tools.subConvert': 'External subscription converter',
  'tools.keypair': 'Generate key pairs',
  'tools.serviceActions': 'Service actions',
  'tools.restartCore': 'Restart sing-box',
  'tools.restartPanel': 'Restart S-UI panel',
  'tools.exportDbTitle': 'Export database',
  'tools.excludeStats': 'Exclude statistics history',
  'tools.excludeChanges': 'Exclude change records',
  'tools.export': 'Export',
  'tools.restoreConfirm': 'Restore will replace the current panel database. Make sure you have a usable backup.',
  'tools.restoreDone': 'Database restored. Restarting the panel is recommended.',
  'tools.serviceUnavailable': 'The service will be briefly unavailable.',
  'tools.submitted': 'Submitted {action}',
  'tools.linkConvertTitle': 'Link conversion',
  'tools.shareLink': 'Share link',
  'tools.subConvertTitle': 'Subscription conversion',
  'tools.subscriptionUrl': 'Subscription URL',
  'tools.keyType': 'Key type',
  'tools.optionsServer': 'Options / server name',
  'tools.generate': 'Generate',
  'admin.title': 'Admins',
  'admin.subtitle': 'Accounts, API tokens and audit changes',
  'admin.admins': 'Admins',
  'admin.tokens': 'API Tokens',
  'admin.changes': 'Changes',
  'admin.security': 'Login security',
  'admin.actor': 'Actor',
  'admin.noAdmins': 'No admins',
  'admin.lastLogin': 'Last login {time}',
  'admin.noTokens': 'No extra API tokens',
  'admin.unnamedToken': 'Unnamed token',
  'admin.noChanges': 'No matching changes',
  'admin.changeCred': 'Change admin credentials',
  'admin.currentPassword': 'Current password',
  'admin.newUsername': 'New username',
  'admin.newPassword': 'New password',
  'admin.createToken': 'Create API token',
  'admin.description': 'Description',
  'admin.validDays': 'Valid days (0 for forever)',
  'admin.saveTokenNow': 'Save this token now',
  'admin.done': 'Done',
  'admin.deleteToken': 'Delete token',
  'admin.deleteTokenMsg': 'Clients using this token will immediately lose access.',
  'admin.totp': 'TOTP two-factor authentication',
  'admin.totpEnabled': 'Enabled; login requires a code or recovery code',
  'admin.totpDisabled': 'Disabled',
  'admin.enableTotp': 'Enable two-step verification',
  'admin.totpSetup': 'Import the URI or secret below into an authenticator, then enter the current code.',
  'admin.code6': '6-digit code',
  'admin.disableTotp': 'Disable two-step verification',
  'admin.codeOrRecovery': 'Code or recovery code',
  'admin.recoveryCodes': 'Save recovery codes',
  'admin.saved': 'Saved',
  'admin.passkeys': 'Passkeys',
  'admin.passkeysWebOnly': 'Server enabled; register new passkeys on the web page',
  'admin.passkeysDisabled': 'Not enabled on the server',
  'admin.deletePasskey': 'Delete passkey',
  'admin.deletePasskeyMsg': 'This device can no longer be used for passwordless login.',
  'admin.oidc': 'OIDC SSO',
  'admin.oidcEnabled': 'Enabled; available on the web login page',
  'admin.oidcDisabled': 'Disabled',
  'time.forever': 'Forever',
  'time.expiry': 'Expiry {time}',
  'error.noToken': 'The panel did not return an API token',
  'error.urlRequired': 'Panel URL is required',
  'error.urlInvalid': 'Panel URL is invalid; include http:// or https://',
  'error.tokenRequired': 'API token is required',
  'error.requestFailed': 'Request failed',
  'error.connectionTimeout': 'Connection timed out. Check address and network.',
  'error.connectionError': 'Unable to connect. Check address, certificate and custom headers.',
  'error.badCertificate': 'Panel TLS certificate is invalid',
  'error.receiveTimeout': 'Panel response timed out',
};

const _zhHans = <String, String>{
  'common.cancel': '取消',
  'common.confirm': '确认',
  'common.save': '保存',
  'common.close': '关闭',
  'common.delete': '删除',
  'common.refresh': '刷新',
  'common.refreshed': '已刷新',
  'common.search': '搜索',
  'common.from': '起',
  'common.to': '止',
  'common.all': '全部',
  'common.none': '无',
  'common.details': '详情',
  'common.result': '结果',
  'common.language': '语言',
  'nav.home': '主页',
  'nav.clients': '用户管理',
  'nav.inbounds': '入站管理',
  'nav.outbounds': '出站管理',
  'nav.endpoints': '节点管理',
  'nav.services': '服务管理',
  'nav.tls': 'TLS 设置',
  'nav.config': '核心配置',
  'nav.analytics': '用量与统计',
  'nav.logs': '日志',
  'nav.admin': '管理员',
  'nav.tools': '设置与工具',
  'nav.logout': '退出当前连接',
  'nav.logoutTitle': '退出连接',
  'nav.logoutMessage': '是否同时撤销当前移动端 API Token？',
  'nav.logoutRevoke': '撤销并退出',
  'auth.passkey': '通行密钥',
  'connect.title': '连接 S-UI',
  'connect.subtitle': '连接信息与令牌仅保存在系统安全存储中',
  'connect.name': '连接名称',
  'connect.defaultName': '我的 S-UI',
  'connect.panelUrl': '面板地址（包含 Web Path）',
  'connect.passwordLogin': '账号登录',
  'connect.adminUsername': '管理员用户名',
  'connect.adminPassword': '管理员密码',
  'connect.secondFactor': '两步验证码或恢复码',
  'connect.customHeaders': '自定义请求 Header',
  'connect.cfPreset': '已预置 Cloudflare Access Service Token 字段',
  'connect.headerName': 'Header 名称',
  'connect.headerValue': 'Header 值',
  'connect.addHeader': '添加 Header',
  'connect.verifying': '正在验证…',
  'connect.connect': '连接面板',
  'connect.httpsHint': '建议仅通过 HTTPS 连接。使用 Cloudflare Zero Trust 时，请填写 CF-Access-Client-Id 与 CF-Access-Client-Secret。',
  'dashboard.title': '运行概览',
  'dashboard.restartCore': '重启 sing-box',
  'dashboard.running': '运行中',
  'dashboard.stopped': '已停止',
  'dashboard.memory': '内存',
  'dashboard.disk': '磁盘',
  'dashboard.totalUpload': '累计上传',
  'dashboard.totalDownload': '累计下载',
  'dashboard.resources': '资源',
  'dashboard.users': '用户',
  'dashboard.inbounds': '入站',
  'dashboard.outbounds': '出站',
  'dashboard.nodes': '节点',
  'dashboard.services': '服务',
  'dashboard.onlineStatus': '在线状态',
  'dashboard.restartConfirm': '现有连接可能短暂中断。',
  'dashboard.restartSubmitted': '已提交重启',
  'dashboard.noOnline': '暂无在线项',
  'resource.subtitle': '完整字段编辑与搜索，兼容 sing-box 新协议字段',
  'resource.bulk': '批量操作',
  'resource.new': '新建',
  'resource.search': '搜索{title}',
  'resource.empty': '没有匹配的数据',
  'resource.deleteTitle': '删除{title}',
  'resource.deleteMessage': '此操作会立即更新 sing-box 配置。',
  'resource.deleted': '已删除',
  'resource.bulkAdd': '批量添加',
  'resource.bulkEdit': '批量编辑',
  'resource.bulkDelete': '批量删除',
  'resource.action': '操作',
  'resource.jsonArray': 'JSON 数组',
  'resource.execute': '执行',
  'resource.checkOk': '连接正常{delay}',
  'resource.checkFailed': '测试失败',
  'resource.userNotFound': '找不到用户详情',
  'resource.subscription': '订阅',
  'resource.jsonSubscription': 'JSON 订阅',
  'resource.clashSubscription': 'Clash 订阅',
  'resource.singboxImport': 'Sing-box 导入',
  'resource.shareLink': '分享链接',
  'resource.qrcode': '二维码',
  'resource.noLinks': '没有可展示的链接',
  'resource.copied': '已复制',
  'resource.copy': '复制',
  'resource.noWireguardPeers': '节点没有可用的 WireGuard Peer 配置',
  'resource.edit': '编辑',
  'resource.clone': '克隆',
  'resource.connectionTest': '连接测试',
  'resource.subscriptionQr': '订阅与二维码',
  'resource.wireguardQr': 'WireGuard 二维码',
  'resource.copyJson': '复制 JSON',
  'resource.jsonCopied': 'JSON 已复制',
  'config.title': '核心配置',
  'config.subtitle': '管理基础、DNS、路由、实验性功能和面板设置',
  'config.basics': '基础',
  'config.routing': '路由',
  'config.experimental': '实验性',
  'config.panelSettings': '面板设置',
  'config.basicInfo': '基础信息',
  'config.routingRulesets': '路由与规则集',
  'config.edit': '编辑',
  'config.editAllSettings': '编辑全部设置',
  'config.panelSubscriptionSettings': '面板与订阅设置',
  'config.configObjectRequired': '配置必须是 JSON 对象',
  'config.settingsObjectRequired': '设置必须是 JSON 对象',
  'config.panelInterface': '面板接口',
  'config.subscriptionService': '订阅服务',
  'config.subscriptionExtensions': '订阅扩展',
  'config.loginIdentity': '登录与身份',
  'editor.visual': '可视化',
  'editor.jsonError': 'JSON 格式错误：{error}',
  'editor.visualHint': '使用选项、开关和输入框编辑；未收录的新 sing-box 字段仍可通过“添加字段”或 JSON 模式维护。',
  'editor.needObject': '可视化编辑需要 JSON 对象，请切换到 JSON 模式',
  'editor.deleteItem': '删除此项',
  'editor.addItem': '添加{item}',
  'editor.deleteField': '删除字段',
  'editor.addField': '添加字段',
  'editor.addConfigField': '添加配置字段',
  'editor.commonField': '常用字段（可选）',
  'editor.fieldName': '字段名',
  'editor.fieldsCount': '{count} 个字段',
  'editor.itemsCount': '{count} 项',
  'editor.onePerLine': '每行一项',
  'editor.item': '项目',
  'editor.valueType': '值类型',
  'editor.text': '文本',
  'editor.number': '数字',
  'editor.bool': '开关',
  'editor.object': '对象',
  'editor.list': '列表',
  'analytics.title': '用量与统计',
  'analytics.subtitle': '按用户、日期与关键词筛选，支持流量汇总和连接详情。',
  'analytics.userUsage': '用户用量',
  'analytics.trafficTrends': '流量趋势',
  'analytics.connections': '连接统计',
  'analytics.userExact': '用户 / 标签（精确，可留空）',
  'analytics.resource': '资源',
  'analytics.upload': '上传',
  'analytics.download': '下载',
  'analytics.total': '合计',
  'analytics.usersCount': '{count} 位用户',
  'analytics.noUsage': '当前筛选范围没有用量数据',
  'analytics.noStats': '当前筛选范围没有统计数据',
  'analytics.noConnections': '当前筛选范围没有连接日志',
  'analytics.quota': '所选日期用量 / 配额 {quota}',
  'analytics.expiry': '到期 {time}',
  'analytics.allTags': '全部标签',
  'analytics.scanned': '已扫描 {count} 条 INFO 日志',
  'analytics.inbounds': '入站',
  'analytics.outbounds': '出站',
  'analytics.nodes': '节点',
  'analytics.destinations': '目标',
  'analytics.lastSeen': '最后出现',
  'analytics.connectionDetails': '连接详情',
  'logs.title': '日志',
  'logs.subtitle': '统一检索系统日志与管理员变更记录，支持 DEBUG、INFO、WARNING、ERROR。',
  'logs.fullText': '全文搜索',
  'logs.user': '用户 / 管理员',
  'logs.level': '级别',
  'logs.empty': '没有匹配的日志',
  'logs.count': '共 {count} 条',
  'tools.title': '设置与工具',
  'tools.subtitle': '连接信息、备份恢复、转换器和服务操作',
  'tools.currentConnection': '当前连接',
  'tools.customHeaders': '自定义 Header',
  'tools.noHeaders': '未配置',
  'tools.reconfigure': '重新配置连接',
  'tools.reconfigureHint': '返回连接页修改地址、Token 或 Cloudflare Header',
  'tools.backupRestore': '备份与恢复',
  'tools.exportDatabase': '导出数据库',
  'tools.restoreDatabase': '恢复数据库',
  'tools.exportSingbox': '导出 sing-box 配置',
  'tools.conversionKeys': '转换与密钥',
  'tools.linkConvert': '分享链接转出站',
  'tools.subConvert': '外部订阅转换',
  'tools.keypair': '生成密钥对',
  'tools.serviceActions': '服务操作',
  'tools.restartCore': '重启 sing-box',
  'tools.restartPanel': '重启 S-UI 面板',
  'tools.exportDbTitle': '导出数据库',
  'tools.excludeStats': '排除统计历史',
  'tools.excludeChanges': '排除变更记录',
  'tools.export': '导出',
  'tools.restoreConfirm': '恢复会替换当前面板数据库，请先确认已有可用备份。',
  'tools.restoreDone': '数据库已恢复，建议重启面板',
  'tools.serviceUnavailable': '服务会短暂不可用。',
  'tools.submitted': '已提交{action}',
  'tools.linkConvertTitle': '链接转换',
  'tools.shareLink': '分享链接',
  'tools.subConvertTitle': '订阅转换',
  'tools.subscriptionUrl': '订阅 URL',
  'tools.keyType': '密钥类型',
  'tools.optionsServer': '选项 / 服务器名称',
  'tools.generate': '生成',
  'admin.title': '管理员',
  'admin.subtitle': '账号、API Token 与变更审计',
  'admin.admins': '管理员',
  'admin.tokens': 'API Token',
  'admin.changes': '变更记录',
  'admin.security': '登录安全',
  'admin.actor': '执行者',
  'admin.noAdmins': '没有管理员',
  'admin.lastLogin': '上次登录 {time}',
  'admin.noTokens': '没有额外 API Token',
  'admin.unnamedToken': '未命名 Token',
  'admin.noChanges': '没有匹配的变更记录',
  'admin.changeCred': '修改管理员凭据',
  'admin.currentPassword': '当前密码',
  'admin.newUsername': '新用户名',
  'admin.newPassword': '新密码',
  'admin.createToken': '创建 API Token',
  'admin.description': '说明',
  'admin.validDays': '有效天数（0 为永久）',
  'admin.saveTokenNow': '请立即保存 Token',
  'admin.done': '完成',
  'admin.deleteToken': '删除 Token',
  'admin.deleteTokenMsg': '使用此 Token 的客户端会立即失去访问权限。',
  'admin.totp': 'TOTP 两步验证',
  'admin.totpEnabled': '已启用；登录需要验证码或恢复码',
  'admin.totpDisabled': '未启用',
  'admin.enableTotp': '启用两步验证',
  'admin.totpSetup': '在验证器中导入下面的 URI 或密钥，然后输入当前验证码。',
  'admin.code6': '6 位验证码',
  'admin.disableTotp': '关闭两步验证',
  'admin.codeOrRecovery': '验证码或恢复码',
  'admin.recoveryCodes': '请保存恢复码',
  'admin.saved': '我已保存',
  'admin.passkeys': '通行密钥',
  'admin.passkeysWebOnly': '服务端已启用；请在 Web 页面注册新通行密钥',
  'admin.passkeysDisabled': '服务端尚未启用',
  'admin.deletePasskey': '删除通行密钥',
  'admin.deletePasskeyMsg': '删除后该设备将不能再用于免密码登录。',
  'admin.oidc': 'OIDC 单点登录',
  'admin.oidcEnabled': '已启用，可从 Web 登录页使用',
  'admin.oidcDisabled': '未启用',
  'time.forever': '永久有效',
  'time.expiry': '到期 {time}',
  'error.noToken': '面板没有返回 API Token',
  'error.urlRequired': '请填写面板地址',
  'error.urlInvalid': '面板地址格式无效，请包含 http:// 或 https://',
  'error.tokenRequired': '请填写 API Token',
  'error.requestFailed': '请求失败',
  'error.connectionTimeout': '连接超时，请检查地址与网络',
  'error.connectionError': '无法连接面板，请检查地址、证书与自定义 Header',
  'error.badCertificate': '面板 TLS 证书无效',
  'error.receiveTimeout': '面板响应超时',
};

const _ja = <String, String>{
  'common.cancel': 'キャンセル',
  'common.confirm': '確認',
  'common.save': '保存',
  'common.close': '閉じる',
  'common.delete': '削除',
  'common.refresh': '更新',
  'common.refreshed': '更新しました',
  'common.search': '検索',
  'common.from': '開始',
  'common.to': '終了',
  'common.all': 'すべて',
  'common.none': 'なし',
  'common.details': '詳細',
  'common.result': '結果',
  'common.language': '言語',
  'nav.home': 'ホーム',
  'nav.clients': 'ユーザー管理',
  'nav.inbounds': 'インバウンド',
  'nav.outbounds': 'アウトバウンド',
  'nav.endpoints': 'ノード管理',
  'nav.services': 'サービス管理',
  'nav.tls': 'TLS 設定',
  'nav.config': 'コア設定',
  'nav.analytics': '使用量と統計',
  'nav.logs': 'ログ',
  'nav.admin': '管理者',
  'nav.tools': '設定とツール',
  'nav.logout': '現在の接続を終了',
  'nav.logoutTitle': '接続を終了',
  'nav.logoutMessage': '現在のモバイル API トークンも取り消しますか？',
  'nav.logoutRevoke': '取り消して終了',
  'auth.passkey': 'パスキー',
  'connect.title': 'S-UI に接続',
  'connect.subtitle': '接続情報とトークンはシステムの安全なストレージにのみ保存されます。',
  'connect.name': '接続名',
  'connect.defaultName': 'My S-UI',
  'connect.panelUrl': 'パネル URL（Web Path を含む）',
  'connect.passwordLogin': 'パスワードログイン',
  'connect.adminUsername': '管理者ユーザー名',
  'connect.adminPassword': '管理者パスワード',
  'connect.secondFactor': '2FA コードまたはリカバリーコード',
  'connect.customHeaders': 'カスタムリクエスト Header',
  'connect.cfPreset': 'Cloudflare Access Service Token フィールドは事前入力済みです',
  'connect.headerName': 'Header 名',
  'connect.headerValue': 'Header 値',
  'connect.addHeader': 'Header を追加',
  'connect.verifying': '検証中…',
  'connect.connect': 'パネルに接続',
  'connect.httpsHint': 'HTTPS を推奨します。Cloudflare Zero Trust では CF-Access-Client-Id と CF-Access-Client-Secret を入力してください。',
  'dashboard.title': '実行概要',
  'dashboard.restartCore': 'sing-box を再起動',
  'dashboard.running': '実行中',
  'dashboard.stopped': '停止',
  'dashboard.memory': 'メモリ',
  'dashboard.disk': 'ディスク',
  'dashboard.totalUpload': '総アップロード',
  'dashboard.totalDownload': '総ダウンロード',
  'dashboard.resources': 'リソース',
  'dashboard.users': 'ユーザー',
  'dashboard.inbounds': 'インバウンド',
  'dashboard.outbounds': 'アウトバウンド',
  'dashboard.nodes': 'ノード',
  'dashboard.services': 'サービス',
  'dashboard.onlineStatus': 'オンライン状態',
  'dashboard.restartConfirm': '既存の接続が短時間中断される可能性があります。',
  'dashboard.restartSubmitted': '再起動を送信しました',
  'dashboard.noOnline': 'オンライン項目はありません',
  'resource.subtitle': 'フルフィールド編集と検索。新しい sing-box プロトコル項目にも対応します。',
  'resource.bulk': '一括操作',
  'resource.new': '新規',
  'resource.search': '{title} を検索',
  'resource.empty': '一致するデータがありません',
  'resource.deleteTitle': '{title} を削除',
  'resource.deleteMessage': 'sing-box 設定をただちに更新します。',
  'resource.deleted': '削除しました',
  'resource.bulkAdd': '一括追加',
  'resource.bulkEdit': '一括編集',
  'resource.bulkDelete': '一括削除',
  'resource.action': '操作',
  'resource.jsonArray': 'JSON 配列',
  'resource.execute': '実行',
  'resource.checkOk': '接続 OK{delay}',
  'resource.checkFailed': 'テスト失敗',
  'resource.userNotFound': 'ユーザー詳細が見つかりません',
  'resource.subscription': 'サブスクリプション',
  'resource.jsonSubscription': 'JSON サブスクリプション',
  'resource.clashSubscription': 'Clash サブスクリプション',
  'resource.singboxImport': 'Sing-box インポート',
  'resource.shareLink': '共有リンク',
  'resource.qrcode': 'QR コード',
  'resource.noLinks': '表示可能なリンクがありません',
  'resource.copied': 'コピーしました',
  'resource.copy': 'コピー',
  'resource.noWireguardPeers': '利用可能な WireGuard Peer 設定がありません',
  'resource.edit': '編集',
  'resource.clone': '複製',
  'resource.connectionTest': '接続テスト',
  'resource.subscriptionQr': 'サブスクリプションと QR コード',
  'resource.wireguardQr': 'WireGuard QR コード',
  'resource.copyJson': 'JSON をコピー',
  'resource.jsonCopied': 'JSON をコピーしました',
  'config.title': 'コア設定',
  'config.subtitle': '基本、DNS、ルーティング、実験機能、パネル設定を管理します。',
  'config.basics': '基本',
  'config.routing': 'ルーティング',
  'config.experimental': '実験的',
  'config.panelSettings': 'パネル設定',
  'config.basicInfo': '基本情報',
  'config.routingRulesets': 'ルーティングとルールセット',
  'config.edit': '編集',
  'config.editAllSettings': 'すべての設定を編集',
  'config.panelSubscriptionSettings': 'パネルとサブスクリプション設定',
  'config.configObjectRequired': '設定は JSON オブジェクトである必要があります',
  'config.settingsObjectRequired': '設定は JSON オブジェクトである必要があります',
  'config.panelInterface': 'パネルインターフェース',
  'config.subscriptionService': 'サブスクリプションサービス',
  'config.subscriptionExtensions': 'サブスクリプション拡張',
  'config.loginIdentity': 'ログインと ID',
  'editor.visual': 'ビジュアル',
  'editor.jsonError': 'JSON エラー: {error}',
  'editor.visualHint': '選択肢、スイッチ、入力欄で編集します。未収録の sing-box 項目は「フィールド追加」または JSON モードで保守できます。',
  'editor.needObject': 'ビジュアル編集には JSON オブジェクトが必要です。JSON モードに切り替えてください。',
  'editor.deleteItem': 'この項目を削除',
  'editor.addItem': '{item}を追加',
  'editor.deleteField': 'フィールドを削除',
  'editor.addField': 'フィールドを追加',
  'editor.addConfigField': '設定フィールドを追加',
  'editor.commonField': 'よく使うフィールド（任意）',
  'editor.fieldName': 'フィールド名',
  'editor.fieldsCount': '{count} 個のフィールド',
  'editor.itemsCount': '{count} 件',
  'editor.onePerLine': '1 行に 1 件',
  'editor.item': '項目',
  'editor.valueType': '値の種類',
  'editor.text': 'テキスト',
  'editor.number': '数値',
  'editor.bool': 'スイッチ',
  'editor.object': 'オブジェクト',
  'editor.list': 'リスト',
  'analytics.title': '使用量と統計',
  'analytics.subtitle': 'ユーザー、日付、キーワードで絞り込み、トラフィック集計と接続詳細を確認できます。',
  'analytics.userUsage': 'ユーザー使用量',
  'analytics.trafficTrends': 'トラフィック推移',
  'analytics.connections': '接続統計',
  'analytics.userExact': 'ユーザー / タグ（完全一致、任意）',
  'analytics.resource': 'リソース',
  'analytics.upload': 'アップロード',
  'analytics.download': 'ダウンロード',
  'analytics.total': '合計',
  'analytics.usersCount': '{count} ユーザー',
  'analytics.noUsage': 'この範囲に使用量データはありません',
  'analytics.noStats': 'この範囲に統計データはありません',
  'analytics.noConnections': 'この範囲に接続ログはありません',
  'analytics.quota': '選択範囲 / クォータ {quota}',
  'analytics.expiry': '期限 {time}',
  'analytics.allTags': 'すべてのタグ',
  'analytics.scanned': '{count} 件の INFO ログをスキャンしました',
  'analytics.inbounds': 'インバウンド',
  'analytics.outbounds': 'アウトバウンド',
  'analytics.nodes': 'ノード',
  'analytics.destinations': '宛先',
  'analytics.lastSeen': '最終検出',
  'analytics.connectionDetails': '接続詳細',
  'logs.title': 'ログ',
  'logs.subtitle': 'システムログと管理者変更を検索します。DEBUG、INFO、WARNING、ERROR に対応します。',
  'logs.fullText': '全文検索',
  'logs.user': 'ユーザー / 管理者',
  'logs.level': 'レベル',
  'logs.empty': '一致するログがありません',
  'logs.count': '{count} 件',
  'tools.title': '設定とツール',
  'tools.subtitle': '接続情報、バックアップ復元、変換ツール、サービス操作',
  'tools.currentConnection': '現在の接続',
  'tools.customHeaders': 'カスタム Header',
  'tools.noHeaders': '未設定',
  'tools.reconfigure': '接続を再設定',
  'tools.reconfigureHint': '接続画面に戻って URL、Token、Cloudflare Header を変更します',
  'tools.backupRestore': 'バックアップと復元',
  'tools.exportDatabase': 'データベースをエクスポート',
  'tools.restoreDatabase': 'データベースを復元',
  'tools.exportSingbox': 'sing-box 設定をエクスポート',
  'tools.conversionKeys': '変換とキー',
  'tools.linkConvert': '共有リンクを outbound に変換',
  'tools.subConvert': '外部サブスクリプション変換',
  'tools.keypair': 'キーペア生成',
  'tools.serviceActions': 'サービス操作',
  'tools.restartCore': 'sing-box を再起動',
  'tools.restartPanel': 'S-UI パネルを再起動',
  'tools.exportDbTitle': 'データベースをエクスポート',
  'tools.excludeStats': '統計履歴を除外',
  'tools.excludeChanges': '変更記録を除外',
  'tools.export': 'エクスポート',
  'tools.restoreConfirm': '復元すると現在のパネルデータベースが置き換わります。利用可能なバックアップを確認してください。',
  'tools.restoreDone': 'データベースを復元しました。パネルの再起動を推奨します',
  'tools.serviceUnavailable': 'サービスが短時間利用できなくなります。',
  'tools.submitted': '{action}を送信しました',
  'tools.linkConvertTitle': 'リンク変換',
  'tools.shareLink': '共有リンク',
  'tools.subConvertTitle': 'サブスクリプション変換',
  'tools.subscriptionUrl': 'サブスクリプション URL',
  'tools.keyType': 'キー種別',
  'tools.optionsServer': 'オプション / サーバー名',
  'tools.generate': '生成',
  'admin.title': '管理者',
  'admin.subtitle': 'アカウント、API Token、変更監査',
  'admin.admins': '管理者',
  'admin.tokens': 'API Token',
  'admin.changes': '変更記録',
  'admin.security': 'ログインセキュリティ',
  'admin.actor': '実行者',
  'admin.noAdmins': '管理者がいません',
  'admin.lastLogin': '最終ログイン {time}',
  'admin.noTokens': '追加 API Token はありません',
  'admin.unnamedToken': '無名 Token',
  'admin.noChanges': '一致する変更記録がありません',
  'admin.changeCred': '管理者認証情報を変更',
  'admin.currentPassword': '現在のパスワード',
  'admin.newUsername': '新しいユーザー名',
  'admin.newPassword': '新しいパスワード',
  'admin.createToken': 'API Token を作成',
  'admin.description': '説明',
  'admin.validDays': '有効日数（0 は無期限）',
  'admin.saveTokenNow': 'この Token を今すぐ保存してください',
  'admin.done': '完了',
  'admin.deleteToken': 'Token を削除',
  'admin.deleteTokenMsg': 'この Token を使うクライアントは直ちにアクセスできなくなります。',
  'admin.totp': 'TOTP 二要素認証',
  'admin.totpEnabled': '有効。ログインにはコードまたはリカバリーコードが必要です',
  'admin.totpDisabled': '無効',
  'admin.enableTotp': '二段階認証を有効化',
  'admin.totpSetup': '認証アプリに URI またはシークレットを登録し、現在のコードを入力してください。',
  'admin.code6': '6 桁コード',
  'admin.disableTotp': '二段階認証を無効化',
  'admin.codeOrRecovery': 'コードまたはリカバリーコード',
  'admin.recoveryCodes': 'リカバリーコードを保存',
  'admin.saved': '保存しました',
  'admin.passkeys': 'パスキー',
  'admin.passkeysWebOnly': 'サーバー側で有効です。新しいパスキーは Web ページで登録してください',
  'admin.passkeysDisabled': 'サーバー側で有効化されていません',
  'admin.deletePasskey': 'パスキーを削除',
  'admin.deletePasskeyMsg': 'このデバイスはパスワードレスログインに使えなくなります。',
  'admin.oidc': 'OIDC SSO',
  'admin.oidcEnabled': '有効。Web ログインページで利用できます',
  'admin.oidcDisabled': '無効',
  'time.forever': '無期限',
  'time.expiry': '期限 {time}',
  'error.noToken': 'パネルが API Token を返しませんでした',
  'error.urlRequired': 'パネル URL が必要です',
  'error.urlInvalid': 'パネル URL が無効です。http:// または https:// を含めてください',
  'error.tokenRequired': 'API Token が必要です',
  'error.requestFailed': 'リクエストに失敗しました',
  'error.connectionTimeout': '接続がタイムアウトしました。アドレスとネットワークを確認してください。',
  'error.connectionError': '接続できません。アドレス、証明書、カスタム Header を確認してください。',
  'error.badCertificate': 'パネルの TLS 証明書が無効です',
  'error.receiveTimeout': 'パネル応答がタイムアウトしました',
};

const _fr = <String, String>{
  'common.cancel': 'Annuler',
  'common.confirm': 'Confirmer',
  'common.save': 'Enregistrer',
  'common.close': 'Fermer',
  'common.delete': 'Supprimer',
  'common.refresh': 'Actualiser',
  'common.refreshed': 'Actualisé',
  'common.search': 'Rechercher',
  'common.from': 'Du',
  'common.to': 'Au',
  'common.all': 'Tous',
  'common.none': 'Aucun',
  'common.details': 'Détails',
  'common.result': 'Résultat',
  'common.language': 'Langue',
  'nav.home': 'Accueil',
  'nav.clients': 'Utilisateurs',
  'nav.inbounds': 'Entrées',
  'nav.outbounds': 'Sorties',
  'nav.endpoints': 'Nœuds',
  'nav.services': 'Services',
  'nav.tls': 'TLS',
  'nav.config': 'Configuration cœur',
  'nav.analytics': 'Usage et statistiques',
  'nav.logs': 'Journaux',
  'nav.admin': 'Administrateurs',
  'nav.tools': 'Paramètres et outils',
  'nav.logout': 'Quitter la connexion actuelle',
  'nav.logoutTitle': 'Quitter la connexion',
  'nav.logoutMessage': 'Révoquer aussi le token API mobile actuel ?',
  'nav.logoutRevoke': 'Révoquer et quitter',
  'auth.passkey': 'Passkey',
  'connect.title': 'Connexion à S-UI',
  'connect.subtitle': 'Les informations de connexion et tokens restent dans le stockage sécurisé du système.',
  'connect.name': 'Nom de connexion',
  'connect.defaultName': 'Mon S-UI',
  'connect.panelUrl': 'URL du panneau (avec Web Path)',
  'connect.passwordLogin': 'Connexion par mot de passe',
  'connect.adminUsername': 'Nom administrateur',
  'connect.adminPassword': 'Mot de passe administrateur',
  'connect.secondFactor': 'Code 2FA ou code de récupération',
  'connect.customHeaders': 'Headers de requête personnalisés',
  'connect.cfPreset': 'Les champs Cloudflare Access Service Token sont préremplis',
  'connect.headerName': 'Nom du Header',
  'connect.headerValue': 'Valeur du Header',
  'connect.addHeader': 'Ajouter un Header',
  'connect.verifying': 'Vérification…',
  'connect.connect': 'Connecter le panneau',
  'connect.httpsHint': 'HTTPS est recommandé. Avec Cloudflare Zero Trust, renseignez CF-Access-Client-Id et CF-Access-Client-Secret.',
  'dashboard.title': 'Vue d’exécution',
  'dashboard.restartCore': 'Redémarrer sing-box',
  'dashboard.running': 'En cours',
  'dashboard.stopped': 'Arrêté',
  'dashboard.memory': 'Mémoire',
  'dashboard.disk': 'Disque',
  'dashboard.totalUpload': 'Envoi total',
  'dashboard.totalDownload': 'Réception totale',
  'dashboard.resources': 'Ressources',
  'dashboard.users': 'Utilisateurs',
  'dashboard.inbounds': 'Entrées',
  'dashboard.outbounds': 'Sorties',
  'dashboard.nodes': 'Nœuds',
  'dashboard.services': 'Services',
  'dashboard.onlineStatus': 'État en ligne',
  'dashboard.restartConfirm': 'Les connexions existantes peuvent être brièvement interrompues.',
  'dashboard.restartSubmitted': 'Redémarrage envoyé',
  'dashboard.noOnline': 'Aucun élément en ligne',
  'resource.subtitle': 'Édition complète des champs et recherche, compatible avec les nouveaux champs de protocole sing-box',
  'resource.bulk': 'Opération groupée',
  'resource.new': 'Nouveau',
  'resource.search': 'Rechercher {title}',
  'resource.empty': 'Aucune donnée correspondante',
  'resource.deleteTitle': 'Supprimer {title}',
  'resource.deleteMessage': 'Cette action met immédiatement à jour la configuration sing-box.',
  'resource.deleted': 'Supprimé',
  'resource.bulkAdd': 'Ajout groupé',
  'resource.bulkEdit': 'Modification groupée',
  'resource.bulkDelete': 'Suppression groupée',
  'resource.action': 'Action',
  'resource.jsonArray': 'Tableau JSON',
  'resource.execute': 'Exécuter',
  'resource.checkOk': 'Connexion réussie{delay}',
  'resource.checkFailed': 'Échec du test',
  'resource.userNotFound': 'Détails utilisateur introuvables',
  'resource.subscription': 'Abonnement',
  'resource.jsonSubscription': 'Abonnement JSON',
  'resource.clashSubscription': 'Abonnement Clash',
  'resource.singboxImport': 'Import sing-box',
  'resource.shareLink': 'Lien de partage',
  'resource.qrcode': 'Code QR',
  'resource.noLinks': 'Aucun lien à afficher',
  'resource.copied': 'Copié',
  'resource.copy': 'Copier',
  'resource.noWireguardPeers': 'Aucune configuration de pair WireGuard disponible',
  'resource.edit': 'Modifier',
  'resource.clone': 'Dupliquer',
  'resource.connectionTest': 'Test de connexion',
  'resource.subscriptionQr': 'Abonnement et code QR',
  'resource.wireguardQr': 'Code QR WireGuard',
  'resource.copyJson': 'Copier le JSON',
  'resource.jsonCopied': 'JSON copié',
  'config.title': 'Configuration cœur',
  'config.subtitle': 'Gérez la base, le DNS, le routage, les fonctions expérimentales et les paramètres du panneau.',
  'config.basics': 'Base',
  'config.routing': 'Routage',
  'config.experimental': 'Expérimental',
  'config.panelSettings': 'Paramètres du panneau',
  'config.basicInfo': 'Informations de base',
  'config.routingRulesets': 'Routage et jeux de règles',
  'config.edit': 'Modifier',
  'config.editAllSettings': 'Modifier tous les paramètres',
  'config.panelSubscriptionSettings': 'Panneau et abonnements',
  'config.configObjectRequired': 'La configuration doit être un objet JSON',
  'config.settingsObjectRequired': 'Les paramètres doivent être un objet JSON',
  'config.panelInterface': 'Interface du panneau',
  'config.subscriptionService': 'Service d’abonnement',
  'config.subscriptionExtensions': 'Extensions d’abonnement',
  'config.loginIdentity': 'Connexion et identité',
  'editor.visual': 'Visuel',
  'editor.jsonError': 'Erreur JSON : {error}',
  'editor.visualHint': 'Modifiez avec des choix, interrupteurs et champs ; les nouveaux champs sing-box restent accessibles via « Ajouter un champ » ou le mode JSON.',
  'editor.needObject': 'L’édition visuelle exige un objet JSON. Passez au mode JSON.',
  'editor.deleteItem': 'Supprimer cet élément',
  'editor.addItem': 'Ajouter {item}',
  'editor.deleteField': 'Supprimer le champ',
  'editor.addField': 'Ajouter un champ',
  'editor.addConfigField': 'Ajouter un champ de configuration',
  'editor.commonField': 'Champ courant (facultatif)',
  'editor.fieldName': 'Nom du champ',
  'editor.fieldsCount': '{count} champs',
  'editor.itemsCount': '{count} éléments',
  'editor.onePerLine': 'Un élément par ligne',
  'editor.item': 'Élément',
  'editor.valueType': 'Type de valeur',
  'editor.text': 'Texte',
  'editor.number': 'Nombre',
  'editor.bool': 'Interrupteur',
  'editor.object': 'Objet',
  'editor.list': 'Liste',
  'analytics.title': 'Usage et statistiques',
  'analytics.subtitle': 'Filtrez par utilisateur, date et mot-clé ; consultez le trafic et les connexions.',
  'analytics.userUsage': 'Usage utilisateur',
  'analytics.trafficTrends': 'Tendances du trafic',
  'analytics.connections': 'Connexions',
  'analytics.userExact': 'Utilisateur / tag (exact, facultatif)',
  'analytics.resource': 'Ressource',
  'analytics.upload': 'Envoi',
  'analytics.download': 'Réception',
  'analytics.total': 'Total',
  'analytics.usersCount': '{count} utilisateurs',
  'analytics.noUsage': 'Aucune donnée d’usage dans cette plage',
  'analytics.noStats': 'Aucune statistique dans cette plage',
  'analytics.noConnections': 'Aucun journal de connexion dans cette plage',
  'analytics.quota': 'Plage sélectionnée / quota {quota}',
  'analytics.expiry': 'Expiration {time}',
  'analytics.allTags': 'Tous les tags',
  'analytics.scanned': '{count} journaux INFO analysés',
  'analytics.inbounds': 'Entrées',
  'analytics.outbounds': 'Sorties',
  'analytics.nodes': 'Nœuds',
  'analytics.destinations': 'Destinations',
  'analytics.lastSeen': 'Dernière occurrence',
  'analytics.connectionDetails': 'Détails de connexion',
  'logs.title': 'Journaux',
  'logs.subtitle': 'Recherche les journaux système et changements admin. DEBUG, INFO, WARNING et ERROR sont pris en charge.',
  'logs.fullText': 'Recherche plein texte',
  'logs.user': 'Utilisateur / admin',
  'logs.level': 'Niveau',
  'logs.empty': 'Aucun journal correspondant',
  'logs.count': '{count} entrées',
  'tools.title': 'Paramètres et outils',
  'tools.subtitle': 'Connexion, sauvegarde/restauration, convertisseurs et opérations de service',
  'tools.currentConnection': 'Connexion actuelle',
  'tools.customHeaders': 'Headers personnalisés',
  'tools.noHeaders': 'Non configuré',
  'tools.reconfigure': 'Reconfigurer la connexion',
  'tools.reconfigureHint': 'Retour à l’écran de connexion pour modifier URL, Token ou Headers Cloudflare',
  'tools.backupRestore': 'Sauvegarde et restauration',
  'tools.exportDatabase': 'Exporter la base',
  'tools.restoreDatabase': 'Restaurer la base',
  'tools.exportSingbox': 'Exporter la configuration sing-box',
  'tools.conversionKeys': 'Conversion et clés',
  'tools.linkConvert': 'Lien de partage vers sortie',
  'tools.subConvert': 'Conversion d’abonnement externe',
  'tools.keypair': 'Générer des paires de clés',
  'tools.serviceActions': 'Actions de service',
  'tools.restartCore': 'Redémarrer sing-box',
  'tools.restartPanel': 'Redémarrer le panneau S-UI',
  'tools.exportDbTitle': 'Exporter la base',
  'tools.excludeStats': 'Exclure l’historique statistique',
  'tools.excludeChanges': 'Exclure les changements',
  'tools.export': 'Exporter',
  'tools.restoreConfirm': 'La restauration remplacera la base actuelle. Vérifiez que vous disposez d’une sauvegarde utilisable.',
  'tools.restoreDone': 'Base restaurée. Redémarrer le panneau est recommandé',
  'tools.serviceUnavailable': 'Le service sera brièvement indisponible.',
  'tools.submitted': '{action} envoyé',
  'tools.linkConvertTitle': 'Conversion de lien',
  'tools.shareLink': 'Lien de partage',
  'tools.subConvertTitle': 'Conversion d’abonnement',
  'tools.subscriptionUrl': 'URL d’abonnement',
  'tools.keyType': 'Type de clé',
  'tools.optionsServer': 'Options / nom de serveur',
  'tools.generate': 'Générer',
  'admin.title': 'Administrateurs',
  'admin.subtitle': 'Comptes, tokens API et audit des changements',
  'admin.admins': 'Administrateurs',
  'admin.tokens': 'Tokens API',
  'admin.changes': 'Changements',
  'admin.security': 'Sécurité de connexion',
  'admin.actor': 'Acteur',
  'admin.noAdmins': 'Aucun administrateur',
  'admin.lastLogin': 'Dernière connexion {time}',
  'admin.noTokens': 'Aucun token API supplémentaire',
  'admin.unnamedToken': 'Token sans nom',
  'admin.noChanges': 'Aucun changement correspondant',
  'admin.changeCred': 'Modifier les identifiants admin',
  'admin.currentPassword': 'Mot de passe actuel',
  'admin.newUsername': 'Nouveau nom d’utilisateur',
  'admin.newPassword': 'Nouveau mot de passe',
  'admin.createToken': 'Créer un token API',
  'admin.description': 'Description',
  'admin.validDays': 'Jours de validité (0 pour toujours)',
  'admin.saveTokenNow': 'Enregistrez ce token maintenant',
  'admin.done': 'Terminé',
  'admin.deleteToken': 'Supprimer le token',
  'admin.deleteTokenMsg': 'Les clients utilisant ce token perdront immédiatement l’accès.',
  'admin.totp': 'Authentification TOTP à deux facteurs',
  'admin.totpEnabled': 'Activée ; la connexion exige un code ou code de récupération',
  'admin.totpDisabled': 'Désactivée',
  'admin.enableTotp': 'Activer la vérification en deux étapes',
  'admin.totpSetup': 'Importez l’URI ou le secret dans un authentificateur, puis saisissez le code actuel.',
  'admin.code6': 'Code à 6 chiffres',
  'admin.disableTotp': 'Désactiver la vérification en deux étapes',
  'admin.codeOrRecovery': 'Code ou code de récupération',
  'admin.recoveryCodes': 'Enregistrer les codes de récupération',
  'admin.saved': 'Enregistré',
  'admin.passkeys': 'Passkeys',
  'admin.passkeysWebOnly': 'Activé côté serveur ; enregistrez les nouveaux passkeys depuis la page Web',
  'admin.passkeysDisabled': 'Non activé côté serveur',
  'admin.deletePasskey': 'Supprimer le passkey',
  'admin.deletePasskeyMsg': 'Cet appareil ne pourra plus être utilisé pour la connexion sans mot de passe.',
  'admin.oidc': 'OIDC SSO',
  'admin.oidcEnabled': 'Activé ; disponible sur la page de connexion Web',
  'admin.oidcDisabled': 'Désactivé',
  'time.forever': 'Toujours',
  'time.expiry': 'Expiration {time}',
  'error.noToken': 'Le panneau n’a pas renvoyé de token API',
  'error.urlRequired': 'L’URL du panneau est requise',
  'error.urlInvalid': 'URL invalide ; incluez http:// ou https://',
  'error.tokenRequired': 'Le token API est requis',
  'error.requestFailed': 'Échec de la requête',
  'error.connectionTimeout': 'Connexion expirée. Vérifiez l’adresse et le réseau.',
  'error.connectionError': 'Connexion impossible. Vérifiez adresse, certificat et headers personnalisés.',
  'error.badCertificate': 'Le certificat TLS du panneau est invalide',
  'error.receiveTimeout': 'Réponse du panneau expirée',
};

const _la = <String, String>{
  'common.cancel': 'Abrogare',
  'common.confirm': 'Confirmare',
  'common.save': 'Servare',
  'common.close': 'Claudere',
  'common.delete': 'Delere',
  'common.refresh': 'Renovare',
  'common.refreshed': 'Renovatum',
  'common.search': 'Quaerere',
  'common.from': 'Ab',
  'common.to': 'Ad',
  'common.all': 'Omnia',
  'common.none': 'Nullum',
  'common.details': 'Singula',
  'common.result': 'Exitus',
  'common.language': 'Lingua',
  'nav.home': 'Domus',
  'nav.clients': 'Usuarii',
  'nav.inbounds': 'Ingressus',
  'nav.outbounds': 'Egressus',
  'nav.endpoints': 'Nodi',
  'nav.services': 'Servitia',
  'nav.tls': 'TLS',
  'nav.config': 'Configuratio nuclei',
  'nav.analytics': 'Usus et statistica',
  'nav.logs': 'Acta',
  'nav.admin': 'Administratores',
  'nav.tools': 'Optiones et instrumenta',
  'nav.logout': 'Coniunctionem praesentem relinquere',
  'nav.logoutTitle': 'Coniunctionem relinquere',
  'nav.logoutMessage': 'Etiam token API mobile praesentem revocare?',
  'nav.logoutRevoke': 'Revocare et exire',
  'auth.passkey': 'Clavis transitus',
  'connect.title': 'Ad S-UI coniungere',
  'connect.subtitle': 'Data coniunctionis et token tantum in repositorio tuto systematis servantur.',
  'connect.name': 'Nomen coniunctionis',
  'connect.defaultName': 'Meum S-UI',
  'connect.panelUrl': 'URL tabulae (cum Web Path)',
  'connect.passwordLogin': 'Ingressus tessera',
  'connect.adminUsername': 'Nomen administratoris',
  'connect.adminPassword': 'Tessera administratoris',
  'connect.secondFactor': 'Codex 2FA aut recuperationis',
  'connect.customHeaders': 'Capita petitionis propria',
  'connect.cfPreset': 'Campi Cloudflare Access Service Token praepleti sunt',
  'connect.headerName': 'Nomen capitis',
  'connect.headerValue': 'Valor capitis',
  'connect.addHeader': 'Caput addere',
  'connect.verifying': 'Probatur…',
  'connect.connect': 'Tabulam coniungere',
  'connect.httpsHint': 'HTTPS commendatur. Pro Cloudflare Zero Trust, CF-Access-Client-Id et CF-Access-Client-Secret insere.',
  'dashboard.title': 'Conspectus cursus',
  'dashboard.restartCore': 'sing-box iterum incipere',
  'dashboard.running': 'Currit',
  'dashboard.stopped': 'Sistit',
  'dashboard.memory': 'Memoria',
  'dashboard.disk': 'Discus',
  'dashboard.totalUpload': 'Missum totum',
  'dashboard.totalDownload': 'Acceptum totum',
  'dashboard.resources': 'Res',
  'dashboard.users': 'Usuarii',
  'dashboard.inbounds': 'Ingressus',
  'dashboard.outbounds': 'Egressus',
  'dashboard.nodes': 'Nodi',
  'dashboard.services': 'Servitia',
  'dashboard.onlineStatus': 'Status in linea',
  'dashboard.restartConfirm': 'Coniunctiones existentes breviter interrumpi possunt.',
  'dashboard.restartSubmitted': 'Reinitium missum',
  'dashboard.noOnline': 'Nulla res in linea',
  'resource.subtitle': 'Omnes campos muta et quaere; campi novi protocollorum sing-box sustinentur',
  'resource.bulk': 'Actio multiplex',
  'resource.new': 'Novum',
  'resource.search': '{title} quaerere',
  'resource.empty': 'Nulla data congruentia',
  'resource.deleteTitle': '{title} delere',
  'resource.deleteMessage': 'Haec actio configurationem sing-box statim renovabit.',
  'resource.deleted': 'Deletum',
  'resource.bulkAdd': 'Plura addere',
  'resource.bulkEdit': 'Plura mutare',
  'resource.bulkDelete': 'Plura delere',
  'resource.action': 'Actio',
  'resource.jsonArray': 'Series JSON',
  'resource.execute': 'Exsequi',
  'resource.checkOk': 'Coniunctio valida{delay}',
  'resource.checkFailed': 'Probatio defecit',
  'resource.userNotFound': 'Singula usoris non inventa',
  'resource.subscription': 'Subscriptio',
  'resource.jsonSubscription': 'Subscriptio JSON',
  'resource.clashSubscription': 'Subscriptio Clash',
  'resource.singboxImport': 'Importatio sing-box',
  'resource.shareLink': 'Nexus communis',
  'resource.qrcode': 'Codex QR',
  'resource.noLinks': 'Nulli nexus monstrandi',
  'resource.copied': 'Exscriptum',
  'resource.copy': 'Exscribere',
  'resource.noWireguardPeers': 'Nulla configuratio WireGuard peer praesto',
  'resource.edit': 'Mutare',
  'resource.clone': 'Duplicare',
  'resource.connectionTest': 'Probatio coniunctionis',
  'resource.subscriptionQr': 'Subscriptio et codex QR',
  'resource.wireguardQr': 'Codex QR WireGuard',
  'resource.copyJson': 'JSON exscribere',
  'resource.jsonCopied': 'JSON exscriptum',
  'config.title': 'Configuratio nuclei',
  'config.subtitle': 'Elementa, DNS, itinera, functiones experimentales et optiones tabulae administra.',
  'config.basics': 'Elementa',
  'config.routing': 'Itinera',
  'config.experimental': 'Experimentale',
  'config.panelSettings': 'Optiones tabulae',
  'config.basicInfo': 'Informatio fundamentalis',
  'config.routingRulesets': 'Itinera et regulae',
  'config.edit': 'Mutare',
  'config.editAllSettings': 'Omnes optiones mutare',
  'config.panelSubscriptionSettings': 'Tabula et subscriptiones',
  'config.configObjectRequired': 'Configuratio debet esse obiectum JSON',
  'config.settingsObjectRequired': 'Optiones debent esse obiectum JSON',
  'config.panelInterface': 'Interfacies tabulae',
  'config.subscriptionService': 'Servitium subscriptionis',
  'config.subscriptionExtensions': 'Extensiones subscriptionis',
  'config.loginIdentity': 'Ingressus et identitas',
  'editor.visual': 'Visibile',
  'editor.jsonError': 'Error JSON: {error}',
  'editor.visualHint': 'Per electiones, commutatores et campos muta; campi novi sing-box per «Campum addere» vel modum JSON tractari possunt.',
  'editor.needObject': 'Mutatio visibilis obiectum JSON requirit. Ad modum JSON transi.',
  'editor.deleteItem': 'Hanc rem delere',
  'editor.addItem': '{item} addere',
  'editor.deleteField': 'Campum delere',
  'editor.addField': 'Campum addere',
  'editor.addConfigField': 'Campum configurationis addere',
  'editor.commonField': 'Campus usitatus (libitum)',
  'editor.fieldName': 'Nomen campi',
  'editor.fieldsCount': '{count} campi',
  'editor.itemsCount': '{count} res',
  'editor.onePerLine': 'Una res per lineam',
  'editor.item': 'Res',
  'editor.valueType': 'Genus valoris',
  'editor.text': 'Textus',
  'editor.number': 'Numerus',
  'editor.bool': 'Commutator',
  'editor.object': 'Obiectum',
  'editor.list': 'Series',
  'analytics.title': 'Usus et statistica',
  'analytics.subtitle': 'Filtra per usorem, diem et verbum; inspice traffic et coniunctiones.',
  'analytics.userUsage': 'Usus usoriorum',
  'analytics.trafficTrends': 'Cursus traffic',
  'analytics.connections': 'Coniunctiones',
  'analytics.userExact': 'Usor / nota (exacte, libitum)',
  'analytics.resource': 'Res',
  'analytics.upload': 'Missum',
  'analytics.download': 'Acceptum',
  'analytics.total': 'Totum',
  'analytics.usersCount': '{count} usuarii',
  'analytics.noUsage': 'Nulla data usus in hoc spatio',
  'analytics.noStats': 'Nulla statistica in hoc spatio',
  'analytics.noConnections': 'Nulla acta coniunctionis in hoc spatio',
  'analytics.quota': 'Spatium electum / quota {quota}',
  'analytics.expiry': 'Exspiratio {time}',
  'analytics.allTags': 'Omnes notae',
  'analytics.scanned': '{count} acta INFO inspecta',
  'analytics.inbounds': 'Ingressus',
  'analytics.outbounds': 'Egressus',
  'analytics.nodes': 'Nodi',
  'analytics.destinations': 'Destinationes',
  'analytics.lastSeen': 'Ultime visum',
  'analytics.connectionDetails': 'Singula coniunctionis',
  'logs.title': 'Acta',
  'logs.subtitle': 'Quaere acta systematis et mutationes administratoris. DEBUG, INFO, WARNING et ERROR sustinentur.',
  'logs.fullText': 'Quaestio plena',
  'logs.user': 'Usor / administrator',
  'logs.level': 'Gradus',
  'logs.empty': 'Nulla acta congruentia',
  'logs.count': '{count} acta',
  'tools.title': 'Optiones et instrumenta',
  'tools.subtitle': 'Coniunctio, copia/restitutio, conversores et actiones servitii',
  'tools.currentConnection': 'Coniunctio praesens',
  'tools.customHeaders': 'Capita propria',
  'tools.noHeaders': 'Non configuratum',
  'tools.reconfigure': 'Coniunctionem iterum configurare',
  'tools.reconfigureHint': 'Ad paginam coniunctionis redi ut URL, Token vel Cloudflare capita mutes',
  'tools.backupRestore': 'Copia et restitutio',
  'tools.exportDatabase': 'Databasim exportare',
  'tools.restoreDatabase': 'Databasim restituere',
  'tools.exportSingbox': 'Configurationem sing-box exportare',
  'tools.conversionKeys': 'Conversio et claves',
  'tools.linkConvert': 'Nexus communis in outbound',
  'tools.subConvert': 'Conversio subscriptionis externae',
  'tools.keypair': 'Paria clavium generare',
  'tools.serviceActions': 'Actiones servitii',
  'tools.restartCore': 'sing-box iterum incipere',
  'tools.restartPanel': 'Tabulam S-UI iterum incipere',
  'tools.exportDbTitle': 'Databasim exportare',
  'tools.excludeStats': 'Historiam statisticam excludere',
  'tools.excludeChanges': 'Acta mutationum excludere',
  'tools.export': 'Exportare',
  'tools.restoreConfirm': 'Restitutio databasim praesentem substituet. Confirma copiam utilem habere.',
  'tools.restoreDone': 'Database restituta est; reinitium tabulae commendatur',
  'tools.serviceUnavailable': 'Servitium breviter non praesto erit.',
  'tools.submitted': '{action} missum est',
  'tools.linkConvertTitle': 'Conversio nexus',
  'tools.shareLink': 'Nexus communis',
  'tools.subConvertTitle': 'Conversio subscriptionis',
  'tools.subscriptionUrl': 'URL subscriptionis',
  'tools.keyType': 'Genus clavis',
  'tools.optionsServer': 'Optiones / nomen servitoris',
  'tools.generate': 'Generare',
  'admin.title': 'Administratores',
  'admin.subtitle': 'Rationes, API Token et audit mutationum',
  'admin.admins': 'Administratores',
  'admin.tokens': 'API Token',
  'admin.changes': 'Mutationes',
  'admin.security': 'Securitas ingressus',
  'admin.actor': 'Actor',
  'admin.noAdmins': 'Nulli administratores',
  'admin.lastLogin': 'Ultimus ingressus {time}',
  'admin.noTokens': 'Nulla API Token addita',
  'admin.unnamedToken': 'Token sine nomine',
  'admin.noChanges': 'Nullae mutationes congruentes',
  'admin.changeCred': 'Credentialia administratoris mutare',
  'admin.currentPassword': 'Tessera praesens',
  'admin.newUsername': 'Nomen usoris novum',
  'admin.newPassword': 'Tessera nova',
  'admin.createToken': 'API Token creare',
  'admin.description': 'Descriptio',
  'admin.validDays': 'Dies validi (0 perpetuum)',
  'admin.saveTokenNow': 'Hoc token nunc serva',
  'admin.done': 'Factum',
  'admin.deleteToken': 'Token delere',
  'admin.deleteTokenMsg': 'Clientes hoc token utentes statim accessum amittent.',
  'admin.totp': 'TOTP duplex probatio',
  'admin.totpEnabled': 'Activum; ingressus codicem vel recuperationem requirit',
  'admin.totpDisabled': 'Inactivum',
  'admin.enableTotp': 'Duplex probatio activare',
  'admin.totpSetup': 'URI vel secretum in authenticatorium importa, deinde codicem praesentem insere.',
  'admin.code6': 'Codex VI digitorum',
  'admin.disableTotp': 'Duplex probatio inactivare',
  'admin.codeOrRecovery': 'Codex aut recuperatio',
  'admin.recoveryCodes': 'Codices recuperationis serva',
  'admin.saved': 'Servatum',
  'admin.passkeys': 'Claves transitus',
  'admin.passkeysWebOnly': 'In servo activum; novas claves in pagina Web registra',
  'admin.passkeysDisabled': 'In servo non activum',
  'admin.deletePasskey': 'Clavem delere',
  'admin.deletePasskeyMsg': 'Hoc instrumentum ad ingressum sine tessera iam uti non poterit.',
  'admin.oidc': 'OIDC SSO',
  'admin.oidcEnabled': 'Activum; in pagina ingressus Web praesto',
  'admin.oidcDisabled': 'Inactivum',
  'time.forever': 'Perpetuum',
  'time.expiry': 'Exspiratio {time}',
  'error.noToken': 'Tabula API Token non reddidit',
  'error.urlRequired': 'URL tabulae requiritur',
  'error.urlInvalid': 'URL tabulae invalidum est; include http:// vel https://',
  'error.tokenRequired': 'API Token requiritur',
  'error.requestFailed': 'Petitio defecit',
  'error.connectionTimeout': 'Coniunctio tempore exacta est. Orationem et rete inspice.',
  'error.connectionError': 'Coniungi non potest. Orationem, certificatum et capita propria inspice.',
  'error.badCertificate': 'Certificatum TLS tabulae invalidum est',
  'error.receiveTimeout': 'Responsum tabulae tempore exactum est',
};

const _vi = <String, String>{
  'common.cancel': 'Hủy', 'common.confirm': 'Xác nhận', 'common.save': 'Lưu', 'common.close': 'Đóng',
  'common.delete': 'Xóa', 'common.refresh': 'Làm mới', 'common.refreshed': 'Đã làm mới', 'common.search': 'Tìm kiếm',
  'common.from': 'Từ', 'common.to': 'Đến', 'common.all': 'Tất cả', 'common.none': 'Không có',
  'common.details': 'Chi tiết', 'common.result': 'Kết quả', 'common.language': 'Ngôn ngữ',
  'nav.home': 'Trang chủ', 'nav.clients': 'Người dùng', 'nav.inbounds': 'Luồng vào', 'nav.outbounds': 'Luồng ra',
  'nav.endpoints': 'Nút mạng', 'nav.services': 'Dịch vụ', 'nav.tls': 'TLS', 'nav.config': 'Cấu hình lõi',
  'nav.analytics': 'Sử dụng và thống kê', 'nav.logs': 'Nhật ký', 'nav.admin': 'Quản trị viên', 'nav.tools': 'Cài đặt và công cụ',
  'nav.logout': 'Thoát kết nối hiện tại', 'nav.logoutTitle': 'Thoát kết nối',
  'nav.logoutMessage': 'Đồng thời thu hồi token API di động hiện tại?', 'nav.logoutRevoke': 'Thu hồi và thoát',
  'auth.passkey': 'Khóa truy cập',
  'connect.title': 'Kết nối với S-UI', 'connect.subtitle': 'Thông tin kết nối và token chỉ được lưu trong kho bảo mật của hệ thống.',
  'connect.name': 'Tên kết nối', 'connect.defaultName': 'S-UI của tôi', 'connect.panelUrl': 'URL bảng điều khiển (gồm cả Web Path)',
  'connect.passwordLogin': 'Đăng nhập bằng mật khẩu', 'connect.adminUsername': 'Tên quản trị viên',
  'connect.adminPassword': 'Mật khẩu quản trị viên', 'connect.secondFactor': 'Mã 2FA hoặc mã khôi phục',
  'connect.customHeaders': 'Header yêu cầu tùy chỉnh', 'connect.cfPreset': 'Đã điền sẵn các trường Cloudflare Access Service Token',
  'connect.headerName': 'Tên Header', 'connect.headerValue': 'Giá trị Header', 'connect.addHeader': 'Thêm Header',
  'connect.verifying': 'Đang xác minh…', 'connect.connect': 'Kết nối bảng điều khiển',
  'connect.httpsHint': 'Nên dùng HTTPS. Với Cloudflare Zero Trust, hãy điền CF-Access-Client-Id và CF-Access-Client-Secret.',
  'dashboard.title': 'Tổng quan hoạt động', 'dashboard.restartCore': 'Khởi động lại sing-box',
  'dashboard.running': 'Đang chạy', 'dashboard.stopped': 'Đã dừng', 'dashboard.memory': 'Bộ nhớ', 'dashboard.disk': 'Ổ đĩa',
  'dashboard.totalUpload': 'Tổng tải lên', 'dashboard.totalDownload': 'Tổng tải xuống', 'dashboard.resources': 'Tài nguyên',
  'dashboard.users': 'Người dùng', 'dashboard.inbounds': 'Luồng vào', 'dashboard.outbounds': 'Luồng ra',
  'dashboard.nodes': 'Nút mạng', 'dashboard.services': 'Dịch vụ', 'dashboard.onlineStatus': 'Trạng thái trực tuyến',
  'dashboard.restartConfirm': 'Các kết nối hiện tại có thể bị gián đoạn trong chốc lát.',
  'dashboard.restartSubmitted': 'Đã gửi yêu cầu khởi động lại', 'dashboard.noOnline': 'Không có mục trực tuyến',
  'resource.subtitle': 'Chỉnh sửa và tìm kiếm đầy đủ trường, tương thích với các trường giao thức sing-box mới',
  'resource.bulk': 'Thao tác hàng loạt', 'resource.new': 'Tạo mới', 'resource.search': 'Tìm {title}',
  'resource.empty': 'Không có dữ liệu phù hợp', 'resource.deleteTitle': 'Xóa {title}',
  'resource.deleteMessage': 'Thao tác này sẽ cập nhật cấu hình sing-box ngay lập tức.', 'resource.deleted': 'Đã xóa',
  'resource.bulkAdd': 'Thêm hàng loạt', 'resource.bulkEdit': 'Sửa hàng loạt', 'resource.bulkDelete': 'Xóa hàng loạt',
  'resource.action': 'Thao tác', 'resource.jsonArray': 'Mảng JSON', 'resource.execute': 'Thực hiện',
  'resource.checkOk': 'Kết nối thành công{delay}', 'resource.checkFailed': 'Kiểm tra thất bại',
  'resource.userNotFound': 'Không tìm thấy chi tiết người dùng', 'resource.subscription': 'Đăng ký',
  'resource.jsonSubscription': 'Đăng ký JSON', 'resource.clashSubscription': 'Đăng ký Clash',
  'resource.singboxImport': 'Nhập sing-box', 'resource.shareLink': 'Liên kết chia sẻ', 'resource.qrcode': 'Mã QR',
  'resource.noLinks': 'Không có liên kết để hiển thị', 'resource.copied': 'Đã sao chép', 'resource.copy': 'Sao chép',
  'resource.noWireguardPeers': 'Không có cấu hình WireGuard peer khả dụng', 'resource.edit': 'Chỉnh sửa',
  'resource.clone': 'Nhân bản', 'resource.connectionTest': 'Kiểm tra kết nối',
  'resource.subscriptionQr': 'Đăng ký và mã QR', 'resource.wireguardQr': 'Mã QR WireGuard',
  'resource.copyJson': 'Sao chép JSON', 'resource.jsonCopied': 'Đã sao chép JSON',
  'config.title': 'Cấu hình lõi', 'config.subtitle': 'Quản lý cơ bản, DNS, định tuyến, tính năng thử nghiệm và cài đặt bảng điều khiển.',
  'config.basics': 'Cơ bản', 'config.routing': 'Định tuyến', 'config.experimental': 'Thử nghiệm',
  'config.panelSettings': 'Cài đặt bảng điều khiển', 'config.basicInfo': 'Thông tin cơ bản',
  'config.routingRulesets': 'Định tuyến và bộ quy tắc', 'config.edit': 'Chỉnh sửa',
  'config.editAllSettings': 'Chỉnh sửa tất cả cài đặt', 'config.panelSubscriptionSettings': 'Bảng điều khiển và đăng ký',
  'config.configObjectRequired': 'Cấu hình phải là một đối tượng JSON', 'config.settingsObjectRequired': 'Cài đặt phải là một đối tượng JSON',
  'config.panelInterface': 'Giao diện bảng điều khiển', 'config.subscriptionService': 'Dịch vụ đăng ký',
  'config.subscriptionExtensions': 'Phần mở rộng đăng ký', 'config.loginIdentity': 'Đăng nhập và danh tính',
  'editor.visual': 'Trực quan', 'editor.jsonError': 'Lỗi JSON: {error}',
  'editor.visualHint': 'Chỉnh sửa bằng lựa chọn, công tắc và ô nhập; trường sing-box mới vẫn có thể được quản lý bằng “Thêm trường” hoặc chế độ JSON.',
  'editor.needObject': 'Chỉnh sửa trực quan cần một đối tượng JSON. Hãy chuyển sang chế độ JSON.',
  'editor.deleteItem': 'Xóa mục này', 'editor.addItem': 'Thêm {item}', 'editor.deleteField': 'Xóa trường',
  'editor.addField': 'Thêm trường', 'editor.addConfigField': 'Thêm trường cấu hình',
  'editor.commonField': 'Trường thường dùng (tùy chọn)', 'editor.fieldName': 'Tên trường',
  'editor.fieldsCount': '{count} trường', 'editor.itemsCount': '{count} mục', 'editor.onePerLine': 'Mỗi dòng một mục',
  'editor.item': 'Mục', 'editor.valueType': 'Kiểu giá trị', 'editor.text': 'Văn bản', 'editor.number': 'Số',
  'editor.bool': 'Công tắc', 'editor.object': 'Đối tượng', 'editor.list': 'Danh sách',
  'analytics.title': 'Sử dụng và thống kê', 'analytics.subtitle': 'Lọc theo người dùng, ngày và từ khóa; xem lưu lượng và chi tiết kết nối.',
  'analytics.userUsage': 'Mức dùng của người dùng', 'analytics.trafficTrends': 'Xu hướng lưu lượng',
  'analytics.connections': 'Kết nối', 'analytics.userExact': 'Người dùng / tag (chính xác, tùy chọn)',
  'analytics.resource': 'Tài nguyên', 'analytics.upload': 'Tải lên', 'analytics.download': 'Tải xuống', 'analytics.total': 'Tổng',
  'analytics.usersCount': '{count} người dùng', 'analytics.noUsage': 'Không có dữ liệu sử dụng trong khoảng này',
  'analytics.noStats': 'Không có thống kê lưu lượng trong khoảng này', 'analytics.noConnections': 'Không có nhật ký kết nối trong khoảng này',
  'analytics.quota': 'Khoảng đã chọn / hạn mức {quota}', 'analytics.expiry': 'Hết hạn {time}', 'analytics.allTags': 'Tất cả tag',
  'analytics.scanned': 'Đã quét {count} nhật ký INFO', 'analytics.inbounds': 'Luồng vào', 'analytics.outbounds': 'Luồng ra', 'analytics.nodes': 'Nút mạng',
  'analytics.destinations': 'Đích', 'analytics.lastSeen': 'Lần cuối xuất hiện', 'analytics.connectionDetails': 'Chi tiết kết nối',
  'logs.title': 'Nhật ký', 'logs.subtitle': 'Tìm kiếm nhật ký hệ thống và thay đổi quản trị. Hỗ trợ DEBUG, INFO, WARNING và ERROR.',
  'logs.fullText': 'Tìm kiếm toàn văn', 'logs.user': 'Người dùng / quản trị viên', 'logs.level': 'Cấp độ',
  'logs.empty': 'Không có nhật ký phù hợp', 'logs.count': '{count} mục',
  'tools.title': 'Cài đặt và công cụ', 'tools.subtitle': 'Kết nối, sao lưu/khôi phục, chuyển đổi và thao tác dịch vụ',
  'tools.currentConnection': 'Kết nối hiện tại', 'tools.customHeaders': 'Header tùy chỉnh', 'tools.noHeaders': 'Chưa cấu hình',
  'tools.reconfigure': 'Cấu hình lại kết nối', 'tools.reconfigureHint': 'Quay lại trang kết nối để sửa URL, Token hoặc Header Cloudflare',
  'tools.backupRestore': 'Sao lưu và khôi phục', 'tools.exportDatabase': 'Xuất cơ sở dữ liệu',
  'tools.restoreDatabase': 'Khôi phục cơ sở dữ liệu', 'tools.exportSingbox': 'Xuất cấu hình sing-box',
  'tools.conversionKeys': 'Chuyển đổi và khóa', 'tools.linkConvert': 'Liên kết chia sẻ sang luồng ra',
  'tools.subConvert': 'Chuyển đổi đăng ký bên ngoài', 'tools.keypair': 'Tạo cặp khóa',
  'tools.serviceActions': 'Thao tác dịch vụ', 'tools.restartCore': 'Khởi động lại sing-box', 'tools.restartPanel': 'Khởi động lại bảng S-UI',
  'tools.exportDbTitle': 'Xuất cơ sở dữ liệu', 'tools.excludeStats': 'Loại trừ lịch sử thống kê',
  'tools.excludeChanges': 'Loại trừ lịch sử thay đổi', 'tools.export': 'Xuất',
  'tools.restoreConfirm': 'Khôi phục sẽ thay thế cơ sở dữ liệu hiện tại. Hãy bảo đảm bạn có bản sao lưu dùng được.',
  'tools.restoreDone': 'Đã khôi phục cơ sở dữ liệu; nên khởi động lại bảng điều khiển',
  'tools.serviceUnavailable': 'Dịch vụ sẽ tạm thời không khả dụng.', 'tools.submitted': 'Đã gửi {action}',
  'tools.linkConvertTitle': 'Chuyển đổi liên kết', 'tools.shareLink': 'Liên kết chia sẻ',
  'tools.subConvertTitle': 'Chuyển đổi đăng ký', 'tools.subscriptionUrl': 'URL đăng ký',
  'tools.keyType': 'Loại khóa', 'tools.optionsServer': 'Tùy chọn / tên máy chủ', 'tools.generate': 'Tạo',
  'admin.title': 'Quản trị viên', 'admin.subtitle': 'Tài khoản, token API và kiểm toán thay đổi',
  'admin.admins': 'Quản trị viên', 'admin.tokens': 'Token API', 'admin.changes': 'Thay đổi', 'admin.security': 'Bảo mật đăng nhập',
  'admin.actor': 'Người thực hiện', 'admin.noAdmins': 'Không có quản trị viên', 'admin.lastLogin': 'Đăng nhập lần cuối {time}',
  'admin.noTokens': 'Không có token API bổ sung', 'admin.unnamedToken': 'Token chưa đặt tên', 'admin.noChanges': 'Không có thay đổi phù hợp',
  'admin.changeCred': 'Đổi thông tin quản trị', 'admin.currentPassword': 'Mật khẩu hiện tại',
  'admin.newUsername': 'Tên người dùng mới', 'admin.newPassword': 'Mật khẩu mới', 'admin.createToken': 'Tạo token API',
  'admin.description': 'Mô tả', 'admin.validDays': 'Số ngày hiệu lực (0 là vĩnh viễn)',
  'admin.saveTokenNow': 'Hãy lưu token ngay bây giờ', 'admin.done': 'Hoàn tất',
  'admin.deleteToken': 'Xóa token', 'admin.deleteTokenMsg': 'Các máy khách dùng token này sẽ mất quyền truy cập ngay lập tức.',
  'admin.totp': 'Xác thực TOTP hai yếu tố', 'admin.totpEnabled': 'Đã bật; đăng nhập cần mã hoặc mã khôi phục',
  'admin.totpDisabled': 'Đã tắt', 'admin.enableTotp': 'Bật xác minh hai bước',
  'admin.totpSetup': 'Nhập URI hoặc khóa vào ứng dụng xác thực rồi điền mã hiện tại.', 'admin.code6': 'Mã 6 chữ số',
  'admin.disableTotp': 'Tắt xác minh hai bước', 'admin.codeOrRecovery': 'Mã xác thực hoặc mã khôi phục',
  'admin.recoveryCodes': 'Lưu mã khôi phục', 'admin.saved': 'Đã lưu',
  'admin.passkeys': 'Khóa truy cập', 'admin.passkeysWebOnly': 'Đã bật trên máy chủ; đăng ký khóa truy cập mới trên trang Web',
  'admin.passkeysDisabled': 'Chưa bật trên máy chủ', 'admin.deletePasskey': 'Xóa khóa truy cập',
  'admin.deletePasskeyMsg': 'Thiết bị này sẽ không thể dùng để đăng nhập không mật khẩu.',
  'admin.oidc': 'OIDC SSO', 'admin.oidcEnabled': 'Đã bật; khả dụng trên trang đăng nhập Web', 'admin.oidcDisabled': 'Đã tắt',
  'time.forever': 'Vĩnh viễn', 'time.expiry': 'Hết hạn {time}',
  'error.noToken': 'Bảng điều khiển không trả về token API', 'error.urlRequired': 'Cần nhập URL bảng điều khiển',
  'error.urlInvalid': 'URL không hợp lệ; hãy gồm http:// hoặc https://', 'error.tokenRequired': 'Cần nhập token API',
  'error.requestFailed': 'Yêu cầu thất bại', 'error.connectionTimeout': 'Kết nối quá thời gian. Hãy kiểm tra địa chỉ và mạng.',
  'error.connectionError': 'Không thể kết nối. Hãy kiểm tra địa chỉ, chứng chỉ và Header tùy chỉnh.',
  'error.badCertificate': 'Chứng chỉ TLS của bảng điều khiển không hợp lệ', 'error.receiveTimeout': 'Phản hồi của bảng điều khiển quá thời gian',
};

const _ru = <String, String>{
  'common.cancel': 'Отмена', 'common.confirm': 'Подтвердить', 'common.save': 'Сохранить', 'common.close': 'Закрыть',
  'common.delete': 'Удалить', 'common.refresh': 'Обновить', 'common.refreshed': 'Обновлено', 'common.search': 'Поиск',
  'common.from': 'С', 'common.to': 'По', 'common.all': 'Все', 'common.none': 'Нет',
  'common.details': 'Подробнее', 'common.result': 'Результат', 'common.language': 'Язык',
  'nav.home': 'Главная', 'nav.clients': 'Пользователи', 'nav.inbounds': 'Входящие', 'nav.outbounds': 'Исходящие',
  'nav.endpoints': 'Узлы', 'nav.services': 'Сервисы', 'nav.tls': 'TLS', 'nav.config': 'Конфигурация ядра',
  'nav.analytics': 'Использование и статистика', 'nav.logs': 'Журналы', 'nav.admin': 'Администраторы', 'nav.tools': 'Настройки и инструменты',
  'nav.logout': 'Завершить текущее подключение', 'nav.logoutTitle': 'Завершить подключение',
  'nav.logoutMessage': 'Также отозвать текущий мобильный API-токен?', 'nav.logoutRevoke': 'Отозвать и выйти',
  'auth.passkey': 'Ключ доступа',
  'connect.title': 'Подключение к S-UI', 'connect.subtitle': 'Данные подключения и токены хранятся только в защищённом хранилище системы.',
  'connect.name': 'Название подключения', 'connect.defaultName': 'Мой S-UI', 'connect.panelUrl': 'URL панели (включая Web Path)',
  'connect.passwordLogin': 'Вход по паролю', 'connect.adminUsername': 'Имя администратора',
  'connect.adminPassword': 'Пароль администратора', 'connect.secondFactor': 'Код 2FA или код восстановления',
  'connect.customHeaders': 'Пользовательские заголовки', 'connect.cfPreset': 'Поля Cloudflare Access Service Token уже добавлены',
  'connect.headerName': 'Имя заголовка', 'connect.headerValue': 'Значение заголовка', 'connect.addHeader': 'Добавить заголовок',
  'connect.verifying': 'Проверка…', 'connect.connect': 'Подключить панель',
  'connect.httpsHint': 'Рекомендуется HTTPS. Для Cloudflare Zero Trust заполните CF-Access-Client-Id и CF-Access-Client-Secret.',
  'dashboard.title': 'Состояние системы', 'dashboard.restartCore': 'Перезапустить sing-box',
  'dashboard.running': 'Работает', 'dashboard.stopped': 'Остановлено', 'dashboard.memory': 'Память', 'dashboard.disk': 'Диск',
  'dashboard.totalUpload': 'Всего отправлено', 'dashboard.totalDownload': 'Всего получено', 'dashboard.resources': 'Ресурсы',
  'dashboard.users': 'Пользователи', 'dashboard.inbounds': 'Входящие', 'dashboard.outbounds': 'Исходящие',
  'dashboard.nodes': 'Узлы', 'dashboard.services': 'Сервисы', 'dashboard.onlineStatus': 'Состояние онлайн',
  'dashboard.restartConfirm': 'Текущие подключения могут кратковременно прерваться.',
  'dashboard.restartSubmitted': 'Перезапуск отправлен', 'dashboard.noOnline': 'Нет активных элементов',
  'resource.subtitle': 'Полное редактирование и поиск полей с поддержкой новых полей протоколов sing-box',
  'resource.bulk': 'Массовая операция', 'resource.new': 'Создать', 'resource.search': 'Поиск: {title}',
  'resource.empty': 'Нет подходящих данных', 'resource.deleteTitle': 'Удалить {title}',
  'resource.deleteMessage': 'Конфигурация sing-box будет обновлена немедленно.', 'resource.deleted': 'Удалено',
  'resource.bulkAdd': 'Массовое добавление', 'resource.bulkEdit': 'Массовое изменение', 'resource.bulkDelete': 'Массовое удаление',
  'resource.action': 'Действие', 'resource.jsonArray': 'Массив JSON', 'resource.execute': 'Выполнить',
  'resource.checkOk': 'Подключение успешно{delay}', 'resource.checkFailed': 'Проверка не пройдена',
  'resource.userNotFound': 'Данные пользователя не найдены', 'resource.subscription': 'Подписка',
  'resource.jsonSubscription': 'Подписка JSON', 'resource.clashSubscription': 'Подписка Clash',
  'resource.singboxImport': 'Импорт sing-box', 'resource.shareLink': 'Ссылка', 'resource.qrcode': 'QR-код',
  'resource.noLinks': 'Нет ссылок для отображения', 'resource.copied': 'Скопировано', 'resource.copy': 'Копировать',
  'resource.noWireguardPeers': 'Нет доступной конфигурации WireGuard peer', 'resource.edit': 'Изменить',
  'resource.clone': 'Клонировать', 'resource.connectionTest': 'Проверка подключения',
  'resource.subscriptionQr': 'Подписка и QR-код', 'resource.wireguardQr': 'QR-код WireGuard',
  'resource.copyJson': 'Копировать JSON', 'resource.jsonCopied': 'JSON скопирован',
  'config.title': 'Конфигурация ядра', 'config.subtitle': 'Управление основными параметрами, DNS, маршрутизацией, экспериментальными функциями и панелью.',
  'config.basics': 'Основное', 'config.routing': 'Маршрутизация', 'config.experimental': 'Экспериментальное',
  'config.panelSettings': 'Настройки панели', 'config.basicInfo': 'Основная информация',
  'config.routingRulesets': 'Маршрутизация и наборы правил', 'config.edit': 'Изменить',
  'config.editAllSettings': 'Изменить все настройки', 'config.panelSubscriptionSettings': 'Панель и подписки',
  'config.configObjectRequired': 'Конфигурация должна быть объектом JSON', 'config.settingsObjectRequired': 'Настройки должны быть объектом JSON',
  'config.panelInterface': 'Интерфейс панели', 'config.subscriptionService': 'Сервис подписок',
  'config.subscriptionExtensions': 'Расширения подписок', 'config.loginIdentity': 'Вход и идентификация',
  'editor.visual': 'Визуально', 'editor.jsonError': 'Ошибка JSON: {error}',
  'editor.visualHint': 'Редактируйте через списки, переключатели и поля; новые поля sing-box доступны через «Добавить поле» или режим JSON.',
  'editor.needObject': 'Для визуального редактирования нужен объект JSON. Переключитесь в режим JSON.',
  'editor.deleteItem': 'Удалить элемент', 'editor.addItem': 'Добавить {item}', 'editor.deleteField': 'Удалить поле',
  'editor.addField': 'Добавить поле', 'editor.addConfigField': 'Добавить поле конфигурации',
  'editor.commonField': 'Часто используемое поле (необязательно)', 'editor.fieldName': 'Имя поля',
  'editor.fieldsCount': 'Полей: {count}', 'editor.itemsCount': 'Элементов: {count}', 'editor.onePerLine': 'Один элемент на строку',
  'editor.item': 'Элемент', 'editor.valueType': 'Тип значения', 'editor.text': 'Текст', 'editor.number': 'Число',
  'editor.bool': 'Переключатель', 'editor.object': 'Объект', 'editor.list': 'Список',
  'analytics.title': 'Использование и статистика', 'analytics.subtitle': 'Фильтруйте по пользователю, дате и ключевому слову; просматривайте трафик и подключения.',
  'analytics.userUsage': 'Трафик пользователей', 'analytics.trafficTrends': 'Динамика трафика',
  'analytics.connections': 'Подключения', 'analytics.userExact': 'Пользователь / тег (точно, необязательно)',
  'analytics.resource': 'Ресурс', 'analytics.upload': 'Отправлено', 'analytics.download': 'Получено', 'analytics.total': 'Всего',
  'analytics.usersCount': 'Пользователей: {count}', 'analytics.noUsage': 'Нет данных об использовании за этот период',
  'analytics.noStats': 'Нет статистики трафика за этот период', 'analytics.noConnections': 'Нет журналов подключений за этот период',
  'analytics.quota': 'Выбранный период / квота {quota}', 'analytics.expiry': 'Истекает {time}', 'analytics.allTags': 'Все теги',
  'analytics.scanned': 'Просканировано INFO-записей: {count}', 'analytics.inbounds': 'Входящие', 'analytics.outbounds': 'Исходящие', 'analytics.nodes': 'Узлы',
  'analytics.destinations': 'Назначения', 'analytics.lastSeen': 'Последняя запись', 'analytics.connectionDetails': 'Сведения о подключении',
  'logs.title': 'Журналы', 'logs.subtitle': 'Поиск системных журналов и изменений администратора. Поддерживаются DEBUG, INFO, WARNING и ERROR.',
  'logs.fullText': 'Полнотекстовый поиск', 'logs.user': 'Пользователь / администратор', 'logs.level': 'Уровень',
  'logs.empty': 'Нет подходящих записей', 'logs.count': 'Записей: {count}',
  'tools.title': 'Настройки и инструменты', 'tools.subtitle': 'Подключение, резервные копии, конвертеры и управление сервисами',
  'tools.currentConnection': 'Текущее подключение', 'tools.customHeaders': 'Пользовательские заголовки', 'tools.noHeaders': 'Не настроено',
  'tools.reconfigure': 'Настроить подключение заново', 'tools.reconfigureHint': 'Вернитесь на экран подключения, чтобы изменить URL, Token или заголовки Cloudflare',
  'tools.backupRestore': 'Резервное копирование и восстановление', 'tools.exportDatabase': 'Экспортировать базу',
  'tools.restoreDatabase': 'Восстановить базу', 'tools.exportSingbox': 'Экспортировать конфигурацию sing-box',
  'tools.conversionKeys': 'Конвертация и ключи', 'tools.linkConvert': 'Ссылка в исходящее подключение',
  'tools.subConvert': 'Конвертация внешней подписки', 'tools.keypair': 'Создать пару ключей',
  'tools.serviceActions': 'Управление сервисами', 'tools.restartCore': 'Перезапустить sing-box', 'tools.restartPanel': 'Перезапустить панель S-UI',
  'tools.exportDbTitle': 'Экспорт базы', 'tools.excludeStats': 'Исключить историю статистики',
  'tools.excludeChanges': 'Исключить историю изменений', 'tools.export': 'Экспортировать',
  'tools.restoreConfirm': 'Восстановление заменит текущую базу. Убедитесь, что у вас есть рабочая резервная копия.',
  'tools.restoreDone': 'База восстановлена; рекомендуется перезапустить панель',
  'tools.serviceUnavailable': 'Сервис будет временно недоступен.', 'tools.submitted': 'Отправлено: {action}',
  'tools.linkConvertTitle': 'Конвертация ссылки', 'tools.shareLink': 'Ссылка',
  'tools.subConvertTitle': 'Конвертация подписки', 'tools.subscriptionUrl': 'URL подписки',
  'tools.keyType': 'Тип ключа', 'tools.optionsServer': 'Параметры / имя сервера', 'tools.generate': 'Создать',
  'admin.title': 'Администраторы', 'admin.subtitle': 'Учётные записи, API-токены и аудит изменений',
  'admin.admins': 'Администраторы', 'admin.tokens': 'API-токены', 'admin.changes': 'Изменения', 'admin.security': 'Безопасность входа',
  'admin.actor': 'Инициатор', 'admin.noAdmins': 'Нет администраторов', 'admin.lastLogin': 'Последний вход {time}',
  'admin.noTokens': 'Нет дополнительных API-токенов', 'admin.unnamedToken': 'Токен без имени', 'admin.noChanges': 'Нет подходящих изменений',
  'admin.changeCred': 'Изменить данные администратора', 'admin.currentPassword': 'Текущий пароль',
  'admin.newUsername': 'Новое имя пользователя', 'admin.newPassword': 'Новый пароль', 'admin.createToken': 'Создать API-токен',
  'admin.description': 'Описание', 'admin.validDays': 'Срок в днях (0 — бессрочно)',
  'admin.saveTokenNow': 'Сохраните токен сейчас', 'admin.done': 'Готово',
  'admin.deleteToken': 'Удалить токен', 'admin.deleteTokenMsg': 'Клиенты с этим токеном немедленно потеряют доступ.',
  'admin.totp': 'Двухфакторная проверка TOTP', 'admin.totpEnabled': 'Включено; для входа нужен код или код восстановления',
  'admin.totpDisabled': 'Выключено', 'admin.enableTotp': 'Включить двухэтапную проверку',
  'admin.totpSetup': 'Добавьте URI или ключ в приложение-аутентификатор и введите текущий код.', 'admin.code6': 'Шестизначный код',
  'admin.disableTotp': 'Отключить двухэтапную проверку', 'admin.codeOrRecovery': 'Код или код восстановления',
  'admin.recoveryCodes': 'Сохраните коды восстановления', 'admin.saved': 'Сохранено',
  'admin.passkeys': 'Ключи доступа', 'admin.passkeysWebOnly': 'Включено на сервере; регистрируйте новые ключи на веб-странице',
  'admin.passkeysDisabled': 'Не включено на сервере', 'admin.deletePasskey': 'Удалить ключ доступа',
  'admin.deletePasskeyMsg': 'Это устройство больше нельзя будет использовать для входа без пароля.',
  'admin.oidc': 'OIDC SSO', 'admin.oidcEnabled': 'Включено; доступно на веб-странице входа', 'admin.oidcDisabled': 'Выключено',
  'time.forever': 'Бессрочно', 'time.expiry': 'Истекает {time}',
  'error.noToken': 'Панель не вернула API-токен', 'error.urlRequired': 'Укажите URL панели',
  'error.urlInvalid': 'Некорректный URL; добавьте http:// или https://', 'error.tokenRequired': 'Укажите API-токен',
  'error.requestFailed': 'Ошибка запроса', 'error.connectionTimeout': 'Время подключения истекло. Проверьте адрес и сеть.',
  'error.connectionError': 'Не удалось подключиться. Проверьте адрес, сертификат и пользовательские заголовки.',
  'error.badCertificate': 'Сертификат TLS панели недействителен', 'error.receiveTimeout': 'Время ожидания ответа панели истекло',
};

const _fa = <String, String>{
  'common.cancel': 'لغو', 'common.confirm': 'تأیید', 'common.save': 'ذخیره', 'common.close': 'بستن',
  'common.delete': 'حذف', 'common.refresh': 'تازه‌سازی', 'common.refreshed': 'تازه شد', 'common.search': 'جستجو',
  'common.from': 'از', 'common.to': 'تا', 'common.all': 'همه', 'common.none': 'هیچ‌کدام',
  'common.details': 'جزئیات', 'common.result': 'نتیجه', 'common.language': 'زبان',
  'nav.home': 'خانه', 'nav.clients': 'کاربران', 'nav.inbounds': 'ورودی‌ها', 'nav.outbounds': 'خروجی‌ها',
  'nav.endpoints': 'گره‌ها', 'nav.services': 'سرویس‌ها', 'nav.tls': 'TLS', 'nav.config': 'پیکربندی هسته',
  'nav.analytics': 'مصرف و آمار', 'nav.logs': 'گزارش‌ها', 'nav.admin': 'مدیران', 'nav.tools': 'تنظیمات و ابزارها',
  'nav.logout': 'خروج از اتصال فعلی', 'nav.logoutTitle': 'خروج از اتصال',
  'nav.logoutMessage': 'توکن API موبایل فعلی نیز لغو شود؟', 'nav.logoutRevoke': 'لغو توکن و خروج',
  'auth.passkey': 'کلید عبور',
  'connect.title': 'اتصال به S-UI', 'connect.subtitle': 'اطلاعات اتصال و توکن‌ها فقط در فضای امن سیستم نگهداری می‌شوند.',
  'connect.name': 'نام اتصال', 'connect.defaultName': 'S-UI من', 'connect.panelUrl': 'نشانی پنل (همراه Web Path)',
  'connect.passwordLogin': 'ورود با گذرواژه', 'connect.adminUsername': 'نام کاربری مدیر',
  'connect.adminPassword': 'گذرواژه مدیر', 'connect.secondFactor': 'کد 2FA یا بازیابی',
  'connect.customHeaders': 'Header سفارشی درخواست', 'connect.cfPreset': 'فیلدهای Cloudflare Access Service Token از پیش افزوده شده‌اند',
  'connect.headerName': 'نام Header', 'connect.headerValue': 'مقدار Header', 'connect.addHeader': 'افزودن Header',
  'connect.verifying': 'در حال بررسی…', 'connect.connect': 'اتصال به پنل',
  'connect.httpsHint': 'استفاده از HTTPS پیشنهاد می‌شود. برای Cloudflare Zero Trust، مقادیر CF-Access-Client-Id و CF-Access-Client-Secret را وارد کنید.',
  'dashboard.title': 'نمای کلی اجرا', 'dashboard.restartCore': 'راه‌اندازی دوباره sing-box',
  'dashboard.running': 'در حال اجرا', 'dashboard.stopped': 'متوقف', 'dashboard.memory': 'حافظه', 'dashboard.disk': 'دیسک',
  'dashboard.totalUpload': 'کل ارسال', 'dashboard.totalDownload': 'کل دریافت', 'dashboard.resources': 'منابع',
  'dashboard.users': 'کاربران', 'dashboard.inbounds': 'ورودی‌ها', 'dashboard.outbounds': 'خروجی‌ها',
  'dashboard.nodes': 'گره‌ها', 'dashboard.services': 'سرویس‌ها', 'dashboard.onlineStatus': 'وضعیت آنلاین',
  'dashboard.restartConfirm': 'ممکن است اتصال‌های موجود برای لحظه‌ای قطع شوند.',
  'dashboard.restartSubmitted': 'درخواست راه‌اندازی دوباره ارسال شد', 'dashboard.noOnline': 'مورد آنلاینی وجود ندارد',
  'resource.subtitle': 'ویرایش و جستجوی کامل فیلدها با پشتیبانی از فیلدهای جدید پروتکل‌های sing-box',
  'resource.bulk': 'عملیات گروهی', 'resource.new': 'جدید', 'resource.search': 'جستجوی {title}',
  'resource.empty': 'داده‌ای مطابق فیلتر نیست', 'resource.deleteTitle': 'حذف {title}',
  'resource.deleteMessage': 'این کار پیکربندی sing-box را بلافاصله به‌روز می‌کند.', 'resource.deleted': 'حذف شد',
  'resource.bulkAdd': 'افزودن گروهی', 'resource.bulkEdit': 'ویرایش گروهی', 'resource.bulkDelete': 'حذف گروهی',
  'resource.action': 'عملیات', 'resource.jsonArray': 'آرایه JSON', 'resource.execute': 'اجرا',
  'resource.checkOk': 'اتصال موفق{delay}', 'resource.checkFailed': 'آزمایش ناموفق بود',
  'resource.userNotFound': 'جزئیات کاربر پیدا نشد', 'resource.subscription': 'اشتراک',
  'resource.jsonSubscription': 'اشتراک JSON', 'resource.clashSubscription': 'اشتراک Clash',
  'resource.singboxImport': 'درون‌ریزی sing-box', 'resource.shareLink': 'پیوند اشتراک‌گذاری', 'resource.qrcode': 'کد QR',
  'resource.noLinks': 'پیوندی برای نمایش وجود ندارد', 'resource.copied': 'کپی شد', 'resource.copy': 'کپی',
  'resource.noWireguardPeers': 'پیکربندی WireGuard peer در دسترس نیست', 'resource.edit': 'ویرایش',
  'resource.clone': 'تکثیر', 'resource.connectionTest': 'آزمایش اتصال',
  'resource.subscriptionQr': 'اشتراک و کد QR', 'resource.wireguardQr': 'کد QR وایرگارد',
  'resource.copyJson': 'کپی JSON', 'resource.jsonCopied': 'JSON کپی شد',
  'config.title': 'پیکربندی هسته', 'config.subtitle': 'تنظیمات پایه، DNS، مسیریابی، قابلیت‌های آزمایشی و پنل را مدیریت کنید.',
  'config.basics': 'پایه', 'config.routing': 'مسیریابی', 'config.experimental': 'آزمایشی',
  'config.panelSettings': 'تنظیمات پنل', 'config.basicInfo': 'اطلاعات پایه',
  'config.routingRulesets': 'مسیریابی و مجموعه قوانین', 'config.edit': 'ویرایش',
  'config.editAllSettings': 'ویرایش همه تنظیمات', 'config.panelSubscriptionSettings': 'پنل و اشتراک‌ها',
  'config.configObjectRequired': 'پیکربندی باید یک شیء JSON باشد', 'config.settingsObjectRequired': 'تنظیمات باید یک شیء JSON باشد',
  'config.panelInterface': 'رابط پنل', 'config.subscriptionService': 'سرویس اشتراک',
  'config.subscriptionExtensions': 'افزونه‌های اشتراک', 'config.loginIdentity': 'ورود و هویت',
  'editor.visual': 'دیداری', 'editor.jsonError': 'خطای JSON: {error}',
  'editor.visualHint': 'با گزینه‌ها، کلیدها و ورودی‌ها ویرایش کنید؛ فیلدهای جدید sing-box همچنان از «افزودن فیلد» یا حالت JSON قابل مدیریت هستند.',
  'editor.needObject': 'ویرایش دیداری به یک شیء JSON نیاز دارد. به حالت JSON بروید.',
  'editor.deleteItem': 'حذف این مورد', 'editor.addItem': 'افزودن {item}', 'editor.deleteField': 'حذف فیلد',
  'editor.addField': 'افزودن فیلد', 'editor.addConfigField': 'افزودن فیلد پیکربندی',
  'editor.commonField': 'فیلد پرکاربرد (اختیاری)', 'editor.fieldName': 'نام فیلد',
  'editor.fieldsCount': '{count} فیلد', 'editor.itemsCount': '{count} مورد', 'editor.onePerLine': 'هر خط یک مورد',
  'editor.item': 'مورد', 'editor.valueType': 'نوع مقدار', 'editor.text': 'متن', 'editor.number': 'عدد',
  'editor.bool': 'کلید', 'editor.object': 'شیء', 'editor.list': 'فهرست',
  'analytics.title': 'مصرف و آمار', 'analytics.subtitle': 'بر اساس کاربر، تاریخ و کلیدواژه فیلتر کنید و ترافیک و جزئیات اتصال را ببینید.',
  'analytics.userUsage': 'مصرف کاربران', 'analytics.trafficTrends': 'روند ترافیک',
  'analytics.connections': 'اتصال‌ها', 'analytics.userExact': 'کاربر / برچسب (دقیق، اختیاری)',
  'analytics.resource': 'منبع', 'analytics.upload': 'ارسال', 'analytics.download': 'دریافت', 'analytics.total': 'مجموع',
  'analytics.usersCount': '{count} کاربر', 'analytics.noUsage': 'در این بازه داده مصرفی وجود ندارد',
  'analytics.noStats': 'در این بازه آمار ترافیک وجود ندارد', 'analytics.noConnections': 'در این بازه گزارش اتصالی وجود ندارد',
  'analytics.quota': 'بازه انتخابی / سهمیه {quota}', 'analytics.expiry': 'انقضا {time}', 'analytics.allTags': 'همه برچسب‌ها',
  'analytics.scanned': '{count} گزارش INFO بررسی شد', 'analytics.inbounds': 'ورودی‌ها', 'analytics.outbounds': 'خروجی‌ها', 'analytics.nodes': 'گره‌ها',
  'analytics.destinations': 'مقصدها', 'analytics.lastSeen': 'آخرین مشاهده', 'analytics.connectionDetails': 'جزئیات اتصال',
  'logs.title': 'گزارش‌ها', 'logs.subtitle': 'جستجوی گزارش‌های سیستم و تغییرات مدیر. DEBUG، INFO، WARNING و ERROR پشتیبانی می‌شوند.',
  'logs.fullText': 'جستجوی متن کامل', 'logs.user': 'کاربر / مدیر', 'logs.level': 'سطح',
  'logs.empty': 'گزارش مطابقی وجود ندارد', 'logs.count': '{count} مورد',
  'tools.title': 'تنظیمات و ابزارها', 'tools.subtitle': 'اتصال، پشتیبان‌گیری و بازیابی، تبدیل‌کننده‌ها و عملیات سرویس',
  'tools.currentConnection': 'اتصال فعلی', 'tools.customHeaders': 'Headerهای سفارشی', 'tools.noHeaders': 'پیکربندی نشده',
  'tools.reconfigure': 'پیکربندی دوباره اتصال', 'tools.reconfigureHint': 'برای تغییر URL، Token یا Headerهای Cloudflare به صفحه اتصال بازگردید',
  'tools.backupRestore': 'پشتیبان‌گیری و بازیابی', 'tools.exportDatabase': 'برون‌ریزی پایگاه داده',
  'tools.restoreDatabase': 'بازیابی پایگاه داده', 'tools.exportSingbox': 'برون‌ریزی پیکربندی sing-box',
  'tools.conversionKeys': 'تبدیل و کلیدها', 'tools.linkConvert': 'پیوند اشتراک‌گذاری به خروجی',
  'tools.subConvert': 'تبدیل اشتراک خارجی', 'tools.keypair': 'تولید جفت‌کلید',
  'tools.serviceActions': 'عملیات سرویس', 'tools.restartCore': 'راه‌اندازی دوباره sing-box', 'tools.restartPanel': 'راه‌اندازی دوباره پنل S-UI',
  'tools.exportDbTitle': 'برون‌ریزی پایگاه داده', 'tools.excludeStats': 'حذف تاریخچه آمار از پشتیبان',
  'tools.excludeChanges': 'حذف تاریخچه تغییرات از پشتیبان', 'tools.export': 'برون‌ریزی',
  'tools.restoreConfirm': 'بازیابی، پایگاه داده فعلی را جایگزین می‌کند. از وجود یک نسخه پشتیبان سالم مطمئن شوید.',
  'tools.restoreDone': 'پایگاه داده بازیابی شد؛ راه‌اندازی دوباره پنل پیشنهاد می‌شود',
  'tools.serviceUnavailable': 'سرویس برای مدت کوتاهی در دسترس نخواهد بود.', 'tools.submitted': '{action} ارسال شد',
  'tools.linkConvertTitle': 'تبدیل پیوند', 'tools.shareLink': 'پیوند اشتراک‌گذاری',
  'tools.subConvertTitle': 'تبدیل اشتراک', 'tools.subscriptionUrl': 'URL اشتراک',
  'tools.keyType': 'نوع کلید', 'tools.optionsServer': 'گزینه‌ها / نام سرور', 'tools.generate': 'تولید',
  'admin.title': 'مدیران', 'admin.subtitle': 'حساب‌ها، توکن‌های API و ممیزی تغییرات',
  'admin.admins': 'مدیران', 'admin.tokens': 'توکن‌های API', 'admin.changes': 'تغییرات', 'admin.security': 'امنیت ورود',
  'admin.actor': 'انجام‌دهنده', 'admin.noAdmins': 'مدیری وجود ندارد', 'admin.lastLogin': 'آخرین ورود {time}',
  'admin.noTokens': 'توکن API اضافه‌ای وجود ندارد', 'admin.unnamedToken': 'توکن بدون نام', 'admin.noChanges': 'تغییر مطابقی وجود ندارد',
  'admin.changeCred': 'تغییر مشخصات مدیر', 'admin.currentPassword': 'گذرواژه فعلی',
  'admin.newUsername': 'نام کاربری جدید', 'admin.newPassword': 'گذرواژه جدید', 'admin.createToken': 'ساخت توکن API',
  'admin.description': 'توضیح', 'admin.validDays': 'روزهای اعتبار (۰ برای دائمی)',
  'admin.saveTokenNow': 'توکن را همین حالا ذخیره کنید', 'admin.done': 'انجام شد',
  'admin.deleteToken': 'حذف توکن', 'admin.deleteTokenMsg': 'کلاینت‌های دارای این توکن فوراً دسترسی خود را از دست می‌دهند.',
  'admin.totp': 'تأیید دومرحله‌ای TOTP', 'admin.totpEnabled': 'فعال است؛ ورود به کد یا کد بازیابی نیاز دارد',
  'admin.totpDisabled': 'غیرفعال', 'admin.enableTotp': 'فعال‌سازی تأیید دومرحله‌ای',
  'admin.totpSetup': 'URI یا کلید را در برنامه احراز هویت وارد و کد فعلی را ثبت کنید.', 'admin.code6': 'کد ۶ رقمی',
  'admin.disableTotp': 'غیرفعال‌سازی تأیید دومرحله‌ای', 'admin.codeOrRecovery': 'کد تأیید یا بازیابی',
  'admin.recoveryCodes': 'کدهای بازیابی را ذخیره کنید', 'admin.saved': 'ذخیره شد',
  'admin.passkeys': 'کلیدهای عبور', 'admin.passkeysWebOnly': 'در سرور فعال است؛ کلید عبور جدید را در صفحه وب ثبت کنید',
  'admin.passkeysDisabled': 'در سرور فعال نشده است', 'admin.deletePasskey': 'حذف کلید عبور',
  'admin.deletePasskeyMsg': 'این دستگاه دیگر برای ورود بدون گذرواژه قابل استفاده نخواهد بود.',
  'admin.oidc': 'ورود یکپارچه OIDC', 'admin.oidcEnabled': 'فعال است و در صفحه ورود وب در دسترس است', 'admin.oidcDisabled': 'غیرفعال',
  'time.forever': 'دائمی', 'time.expiry': 'انقضا {time}',
  'error.noToken': 'پنل توکن API برنگرداند', 'error.urlRequired': 'نشانی پنل لازم است',
  'error.urlInvalid': 'نشانی نامعتبر است؛ http:// یا https:// را وارد کنید', 'error.tokenRequired': 'توکن API لازم است',
  'error.requestFailed': 'درخواست ناموفق بود', 'error.connectionTimeout': 'زمان اتصال تمام شد. نشانی و شبکه را بررسی کنید.',
  'error.connectionError': 'اتصال به پنل ممکن نیست. نشانی، گواهی و Headerهای سفارشی را بررسی کنید.',
  'error.badCertificate': 'گواهی TLS پنل نامعتبر است', 'error.receiveTimeout': 'زمان پاسخ پنل تمام شد',
};

final _messages = <String, Map<String, String>>{
  'en': _en,
  'zhHans': {..._en, ..._zhHans},
  'zhHant': {..._en, ..._zhHans, 'common.language': '語言'},
  'ja': {..._en, ..._ja},
  'fr': {..._en, ..._fr},
  'la': {..._en, ..._la},
  'fa': {..._en, ..._fa},
  'vi': {..._en, ..._vi},
  'ru': {..._en, ..._ru},
};

const _fieldLabelsEn = <String, String>{
  'id': 'ID',
  'type': 'Type',
  'tag': 'Tag',
  'name': 'Name',
  'enable': 'Enabled',
  'enabled': 'Enabled',
  'listen': 'Listen address',
  'listen_port': 'Port',
  'server': 'Server',
  'server_port': 'Server port',
  'tls_id': 'TLS template',
  'transport': 'Transport',
  'tls': 'TLS',
  'client': 'Client',
  'config': 'Protocol config',
  'inbounds': 'Inbounds',
  'outbounds': 'Outbounds',
  'volume': 'Traffic quota',
  'expiry': 'Expiry',
  'desc': 'Description',
  'group': 'Group',
  'delayStart': 'Delayed start',
  'autoReset': 'Auto reset',
  'resetDays': 'Reset days',
  'nextReset': 'Next reset',
  'up': 'Upload',
  'down': 'Download',
  'username': 'Username',
  'user': 'User',
  'password': 'Password',
  'uuid': 'UUID',
  'flow': 'Flow',
  'method': 'Method',
  'network': 'Network',
  'version': 'Version',
  'security': 'Security',
  'packet_encoding': 'Packet encoding',
  'alter_id': 'Alter ID',
  'address': 'Address',
  'private_key': 'Private key',
  'public_key': 'Public key',
  'pre_shared_key': 'Pre-shared key',
  'allowed_ips': 'Allowed IPs',
  'peers': 'Peers',
  'users': 'Users',
  'links': 'Links',
  'remark': 'Remark',
  'uri': 'URI',
  'headers': 'Headers',
  'extra_headers': 'Extra headers',
  'path': 'Path',
  'domain': 'Domain',
  'rules': 'Rules',
  'rule_set': 'Rule sets',
  'action': 'Action',
  'mode': 'Mode',
  'invert': 'Invert result',
  'final': 'Default outbound',
  'strategy': 'Strategy',
  'level': 'Log level',
  'output': 'Log file',
  'timestamp': 'Timestamp',
  'disabled': 'Disabled',
  'experimental': 'Experimental',
  'dns': 'DNS',
  'route': 'Route',
  'log': 'Log',
  'ntp': 'NTP',
  'servers': 'Servers',
  'format': 'Format',
  'url': 'URL',
  'certificate': 'Certificate content',
  'certificate_path': 'Certificate path',
  'key': 'Key content',
  'key_path': 'Key path',
  'server_name': 'Server name',
  'insecure': 'Allow insecure',
  'disable_sni': 'Disable SNI',
  'alpn': 'ALPN',
  'min_version': 'Minimum TLS version',
  'max_version': 'Maximum TLS version',
  'cipher_suites': 'Cipher suites',
  'curve_preferences': 'Curve preferences',
  'reality': 'Reality',
  'acme': 'ACME',
  'ech': 'ECH',
  'utls': 'uTLS',
  'multiplex': 'Multiplex',
  'brutal': 'Brutal',
  'padding': 'Padding',
  'congestion_control': 'Congestion control',
  'zero_rtt_handshake': '0-RTT handshake',
  'webListen': 'Panel listen address',
  'webPort': 'Panel port',
  'webPath': 'Panel path',
  'webDomain': 'Panel domain',
  'webCertFile': 'Panel certificate path',
  'webKeyFile': 'Panel key path',
  'webURI': 'Panel URI',
  'sessionMaxAge': 'Session max age',
  'trafficAge': 'Traffic retention days',
  'timeLocation': 'Time zone',
  'subListen': 'Subscription listen address',
  'subPort': 'Subscription port',
  'subPath': 'Subscription path',
  'subDomain': 'Subscription domain',
  'subCertFile': 'Subscription certificate path',
  'subKeyFile': 'Subscription key path',
  'subUpdates': 'Update interval',
  'subEncode': 'Enable Base64',
  'subShowInfo': 'Enable user info',
  'subURI': 'Subscription URI',
  'subJsonExt': 'JSON subscription extension',
  'subClashExt': 'Clash subscription extension',
};

const _fieldLabelsZhHans = <String, String>{
  'id': 'ID',
  'type': '类型',
  'tag': '标签',
  'name': '名称',
  'enable': '启用',
  'enabled': '启用',
  'listen': '监听地址',
  'listen_port': '端口',
  'server': '服务器',
  'server_port': '服务器端口',
  'tls_id': 'TLS 模板',
  'transport': '传输',
  'tls': 'TLS',
  'client': '客户端',
  'config': '协议配置',
  'inbounds': '入站',
  'outbounds': '出站',
  'volume': '流量配额',
  'expiry': '到期时间',
  'desc': '描述',
  'group': '分组',
  'delayStart': '延迟启动',
  'autoReset': '自动重置',
  'resetDays': '重置天数',
  'nextReset': '下次重置',
  'up': '上传',
  'down': '下载',
  'username': '用户名',
  'user': '用户',
  'password': '密码',
  'uuid': 'UUID',
  'flow': '流控',
  'method': '加密方式',
  'network': '网络',
  'version': '版本',
  'security': '安全选项',
  'packet_encoding': '数据包编码',
  'alter_id': 'Alter ID',
  'address': '地址',
  'private_key': '私钥',
  'public_key': '公钥',
  'pre_shared_key': '预共享密钥',
  'allowed_ips': '允许的 IP',
  'peers': 'Peer 列表',
  'users': '用户列表',
  'links': '链接',
  'remark': '备注',
  'uri': '链接地址',
  'headers': '请求头',
  'extra_headers': '额外请求头',
  'path': '路径',
  'domain': '域名',
  'rules': '规则',
  'rule_set': '规则集',
  'action': '操作',
  'mode': '逻辑模式',
  'invert': '反选结果',
  'final': '默认出站',
  'strategy': '策略',
  'level': '日志级别',
  'output': '日志文件',
  'timestamp': '时间戳',
  'disabled': '禁用',
  'experimental': '实验性功能',
  'dns': 'DNS',
  'route': '路由',
  'log': '日志',
  'ntp': 'NTP',
  'servers': '服务器列表',
  'format': '格式',
  'url': 'URL',
  'certificate': '证书内容',
  'certificate_path': '证书路径',
  'key': '密钥内容',
  'key_path': '密钥路径',
  'server_name': '服务器名称',
  'insecure': '允许不安全',
  'disable_sni': '禁用 SNI',
  'alpn': 'ALPN',
  'min_version': '最低 TLS 版本',
  'max_version': '最高 TLS 版本',
  'cipher_suites': '密码套件',
  'curve_preferences': '曲线偏好',
  'reality': 'Reality',
  'acme': 'ACME',
  'ech': 'ECH',
  'utls': 'uTLS',
  'multiplex': '多路复用',
  'brutal': 'Brutal',
  'padding': '填充',
  'congestion_control': '拥塞控制',
  'zero_rtt_handshake': '0-RTT 握手',
  'webListen': '面板监听地址',
  'webPort': '面板端口',
  'webPath': '面板路径',
  'webDomain': '面板域名',
  'webCertFile': '面板证书路径',
  'webKeyFile': '面板密钥路径',
  'webURI': '面板 URI',
  'sessionMaxAge': '会话有效期',
  'trafficAge': '流量保留天数',
  'timeLocation': '时区',
  'subListen': '订阅监听地址',
  'subPort': '订阅端口',
  'subPath': '订阅路径',
  'subDomain': '订阅域名',
  'subCertFile': '订阅证书路径',
  'subKeyFile': '订阅密钥路径',
  'subUpdates': '更新间隔',
  'subEncode': '启用 Base64',
  'subShowInfo': '启用用户信息',
  'subURI': '订阅 URI',
  'subJsonExt': 'JSON 订阅扩展',
  'subClashExt': 'Clash 订阅扩展',
};

const _singularLabelsEn = <String, String>{
  'peers': 'Peer',
  'users': 'User',
  'links': 'Link',
  'rules': 'Rule',
  'rule_set': 'Rule set',
  'servers': 'Server',
};

const _singularLabelsZhHans = <String, String>{
  'peers': 'Peer',
  'users': '用户',
  'links': '链接',
  'rules': '规则',
  'rule_set': '规则集',
  'servers': '服务器',
};
